# Labelled learner answers for the two checks in Rafiq worth replacing.
# ok = should the app accept this answer?  err = main problem (Arabic cases only).

# (arabic word, glosses exactly as in vocab-data.js, what the learner typed, ok)
VOCAB = [
    ("ذَهَبَ / يَذْهَبُ", "to go", "to go", True),
    ("ذَهَبَ / يَذْهَبُ", "to go", "go", True),
    ("ذَهَبَ / يَذْهَبُ", "to go", "went", True),
    ("ذَهَبَ / يَذْهَبُ", "to go", "to come", False),
    ("أَنْتَ", "you (m)", "you", True),
    ("أَنْتَ", "you (m)", "you (m)", True),
    ("أَنْتَ", "you (m)", "i", False),
    ("بَيْت", "house", "home", True),
    ("بَيْت", "house", "a house", True),
    ("بَيْت", "house", "room", False),
    ("كِتاب", "book", "bok", True),
    ("كِتاب", "book", "books", True),
    ("كِتاب", "book", "pen", False),
    ("أَب", "father", "dad", True),
    ("أَب", "father", "mother", False),
    ("أُمّ", "mother", "mum", True),
    ("أَكَلَ / يَأْكُلُ", "to eat", "eat", True),
    ("أَكَلَ / يَأْكُلُ", "to eat", "to drink", False),
    ("كَتَبَ / يَكْتُبُ", "to write", "write", True),
    ("كَتَبَ / يَكْتُبُ", "to write", "to read", False),
    ("مُهَنْدِس", "engineer", "enginer", True),
    ("مُهَنْدِس", "engineer", "teacher", False),
    ("غُرْفَة", "room", "bedroom", False),
    ("سَرِير", "bed", "bed", True),
    ("صَحِيفَة", "newspaper", "paper", True),
    ("صَحِيفَة", "newspaper", "magazine", False),
    ("حافِلَة", "bus", "coach", True),
    ("حافِلَة", "bus", "car", False),
    ("مُبَكِّراً", "early", "late", False),
    ("أُسْرَة", "family", "familly", True),
    ("هَذا", "this (m)", "this", True),
    ("هَذا", "this (m)", "that", False),
    ("أَيْنَ", "where", "when", False),
    ("أَيْنَ", "where", "where?", True),
    ("صَباح", "morning", "evening", False),
    ("نافِذة", "window", "windows", True),
    ("نامَ / يَنامُ", "to sleep", "sleep", True),
    ("سُوق", "market", "marketplace", True),
    ("سُوق", "market", "shop", False),
    ("مُسْتَشْفى", "hospital", "clinic", False),
    ("قَلَم", "pen", "pencil", True),
    ("تِسْعَة", "nine", "9", True),
    ("تِسْعَة", "nine", "ninety", False),
]

# (model answer, English prompt, learner answer, ok, main error)
PRODUCE = [
    ("أَنا مِنْ مِصْرَ.", "I'm from Egypt.", "انا من مصر", True, "none"),
    ("أَنا مِنْ مِصْرَ.", "I'm from Egypt.", "أَنَا مِنْ مِصْرَ", True, "none"),
    ("أَنا مِنْ مِصْرَ.", "I'm from Egypt.", "أنا", False, "missing_word"),
    ("أَنا مِنْ مِصْرَ.", "I'm from Egypt.", "انا من مسر", False, "spelling"),
    ("هَلْ أَنْتَ طالِبٌ؟", "Are you a student?", "أأنت طالب؟", True, "none"),
    ("هَلْ أَنْتَ طالِبٌ؟", "Are you a student?", "هل أنت مدرس؟", False, "wrong_word"),
    ("اسْمِي عُمَرُ. وَما اسْمُكَ أَنْتَ؟", "My name is Umar. And what's yours?", "اسمي عمر وما اسمك", True, "none"),
    ("اسْمِي عُمَرُ. وَما اسْمُكَ أَنْتَ؟", "My name is Umar. And what's yours?", "اسمك عمر وما اسمي انت", False, "different_meaning"),
    ("هَذا وَالِدِي، وَهَذِهِ وَالِدَتِي.", "This is my father, and this is my mother.", "هذا ابي وهذه امي", True, "none"),
    ("هَذا وَالِدِي، وَهَذِهِ وَالِدَتِي.", "This is my father, and this is my mother.", "هذه والدي وهذا والدتي", False, "gender_agreement"),
    ("أُسْرَتُكَ كَبِيرَةٌ، ما شاءَ اللهُ.", "Your family is big, mashallah.", "أسرتك كبير ما شاء الله", False, "gender_agreement"),
    ("أُسْرَتُكَ كَبِيرَةٌ، ما شاءَ اللهُ.", "Your family is big, mashallah.", "عائلتك كبيرة ما شاء الله", True, "none"),
    ("أُسْرَتُكَ كَبِيرَةٌ، ما شاءَ اللهُ.", "Your family is big, mashallah.", "أسرتك صغيرة ما شاء الله", False, "different_meaning"),
    ("أَيْنَ تَسْكُنُ؟", "Where do you live?", "اين تسكن", True, "none"),
    ("أَيْنَ تَسْكُنُ؟", "Where do you live?", "أين يسكن", False, "wrong_person_or_tense"),
    ("أَسْكُنُ فِي شَقَّةٍ فِي حَيِّ الْجامِعَةِ.", "I live in a flat in the university district.", "أسكن في شقة في حي الجامعة", True, "none"),
    ("أَسْكُنُ فِي شَقَّةٍ فِي حَيِّ الْجامِعَةِ.", "I live in a flat in the university district.", "تسكن في شقة في حي الجامعة", False, "wrong_person_or_tense"),
    ("كَمْ غُرْفَةً فِيها؟", "How many rooms does it have?", "كم غرفة فيها", True, "none"),
    ("كَمْ غُرْفَةً فِيها؟", "How many rooms does it have?", "كم غرف فيها", False, "grammar_other"),
    ("أَسْتَيْقِظُ مُبَكِّرًا، فِي السَّاعَةِ السَّابِعَةِ صَباحًا.", "I wake up early, at seven in the morning.", "أستيقظ في الساعة السابعة صباحا مبكرا", True, "none"),
    ("أَسْتَيْقِظُ مُبَكِّرًا، فِي السَّاعَةِ السَّابِعَةِ صَباحًا.", "I wake up early, at seven in the morning.", "أستيقظ متأخرا في الساعة السابعة صباحا", False, "different_meaning"),
    ("أَسْتَيْقِظُ مُبَكِّرًا، فِي السَّاعَةِ السَّابِعَةِ صَباحًا.", "I wake up early, at seven in the morning.", "أستيقظ مبكرا في الساعة السادسة صباحا", False, "wrong_word"),
    ("أَذْهَبُ بِالْحافِلَةِ أَوْ بِالسَّيَّارَةِ.", "I go by bus or by car.", "أذهب بالسيارة أو بالحافلة", True, "none"),
    ("أَذْهَبُ بِالْحافِلَةِ أَوْ بِالسَّيَّارَةِ.", "I go by bus or by car.", "ذهبت بالحافلة أو بالسيارة", False, "wrong_person_or_tense"),
    ("مَتى تَسْتَيْقِظُ؟", "When do you wake up?", "متى تستيقظ", True, "none"),
    ("مَتى تَسْتَيْقِظُ؟", "When do you wake up?", "متى استيقظت", False, "wrong_person_or_tense"),
    ("ما جِنْسِيَّتُكَ يا خالِدُ؟", "What's your nationality, Khalid?", "يا خالد ما جنسيتك", True, "none"),
    ("ما جِنْسِيَّتُكَ يا خالِدُ؟", "What's your nationality, Khalid?", "ما اسمك يا خالد", False, "wrong_word"),
    ("هَيَّا بِنا إِلى الْمَسْجِدِ.", "Let's go to the mosque.", "هيا بنا الى المسجد", True, "none"),
    ("هَيَّا بِنا إِلى الْمَسْجِدِ.", "Let's go to the mosque.", "هيا بنا إلى المدرسة", False, "wrong_word"),
    ("أُصَلِّي، ثُمَّ أَقْرَأُ الصَّحِيفَةَ.", "I pray, then I read the newspaper.", "أصلي ثم أقرأ الجريدة", True, "none"),
    ("أُصَلِّي، ثُمَّ أَقْرَأُ الصَّحِيفَةَ.", "I pray, then I read the newspaper.", "أقرأ الصحيفة ثم أصلي", False, "different_meaning"),
    ("أَنا مُهَنْدِسٌ وَ صَدِيقِي مُدَرِّسٌ.", "I am an engineer and my friend is a teacher.", "أنا مهندس وصديقي مدرس", True, "none"),
    ("أَنا مُهَنْدِسٌ وَ صَدِيقِي مُدَرِّسٌ.", "I am an engineer and my friend is a teacher.", "أنا مهندسة و صديقي مدرس", False, "gender_agreement"),
    ("أَنا مُهَنْدِسٌ وَ صَدِيقِي مُدَرِّسٌ.", "I am an engineer and my friend is a teacher.", "صديقي مهندس و أنا مدرس", False, "different_meaning"),
    ("هَذِهِ أُخْتِي، وَهِيَ طالِبَةٌ فِي الْجامِعَةِ", "This is my sister, and she's a student at the university.", "هذه أختي وهي طالبة في الجامعة", True, "none"),
    ("هَذِهِ أُخْتِي، وَهِيَ طالِبَةٌ فِي الْجامِعَةِ", "This is my sister, and she's a student at the university.", "هذه أختي وهو طالب في الجامعة", False, "gender_agreement"),
]
