"""Tag each Transform, Fix-it and Gap-fill exercise with the grammar point it
practises, so the weak-spots review can pick exercises for a learner's repeat
mistakes. TypeSafe chooses from a fixed list; the result is item-tags.js.

    TYPESAFE_API_KEY=... python3 tools/typesafe-exp/tag_items.py

Tags match the mistake types in mistakes.js."""
import json, os, subprocess
from concurrent.futures import ThreadPoolExecutor
from collections import Counter
from run import ask

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
items = json.loads(subprocess.check_output(["node", "-e", r"""
  const fs=require('fs');let s=fs.readFileSync('drills-data.js','utf8').replace(/const\s+(DATA|EXTRA)\s*=/g,'globalThis.$1=');eval(s);
  Object.keys(EXTRA).forEach(k=>{const u=DATA.find(x=>x.n===k);if(u)Object.assign(u,EXTRA[k])});
  const out=[];
  DATA.forEach(u=>{
    (u.transforms||[]).forEach((t,i)=>out.push({id:u.n+'|transform|'+i, text:{task:t.task[1], sentence:t.src, answer:t.ans}}));
    (u.fix||[]).forEach((t,i)=>out.push({id:u.n+'|fix|'+i, text:{wrong:t.bad, corrected:t.good, why:t.w}}));
    (u.cloze||[]).forEach((t,i)=>out.push({id:u.n+'|cloze|'+i, text:{sentence:t.q, options:t.o, answer:t.o[t.a], why:t.w}}));
  });
  console.log(JSON.stringify(out));"""], cwd=ROOT))

Q = {"tag": {"type": "choice",
  "instructions": "An Arabic exercise is described in `exercise`. Which grammar point does it mainly practise?",
  "criteria": {
    "gender_agreement": "Masculine/feminine agreement: هذا/هذه, adjectives, pronouns or verbs matching a noun's gender",
    "wrong_person_or_tense": "Verb person, number or tense: I/you/he/they forms, past/present/future, negating a verb",
    "grammar_other": "Numbers and counting (كم, 3–10 with plurals), case endings, prepositions, particles, or other grammar",
    "meaning": "Mainly vocabulary or meaning: choosing the right word, asking a question about a detail, or word order"}}}

with ThreadPoolExecutor(8) as ex:
    res = list(ex.map(lambda it: ask({"exercise": it["text"]}, Q), items))
tags = {it["id"]: r["answers"]["tag"]["choice"] for it, r in zip(items, res)}
open(os.path.join(ROOT, "item-tags.js"), "w", encoding="utf8").write(
    "/* Generated by tools/typesafe-exp/tag_items.py — the grammar point each exercise practises.\n"
    "   Keys are drill item ids (unit|mode|index); values match the mistake types in mistakes.js. */\n"
    "const ITEM_TAGS = " + json.dumps(tags) + ";\n")
print(len(tags), "items tagged:", dict(Counter(tags.values())))
for it, r in list(zip(items, res))[:: max(1, len(items)//14)]:
    print(f"  {r['answers']['tag']['choice']:<22} {json.dumps(it['text'], ensure_ascii=False)[:110]}")
