/* Real-life scenes (Rafiq Complete): short conversations outside the units,
   played with the conversation partner. The other person speaks first; the
   learner replies in their own words. Lines are [speaker, Arabic, English];
   the learner's lines are only suggestions shown when a reply doesn't fit.
   Checked with tools/typesafe-exp/qa_dialogues.py. */
const SCENES = [
  {id:'airport', pic:'✈️', en:'At the airport', ar:'فِي الْمَطارِ', d:'Passport control on arrival', lines:[
    ['م','السَّلامُ عَلَيْكُمْ. أَعْطِنِي جَوازَ السَّفَرِ، مِنْ فَضْلِكَ.','Peace be upon you. Your passport, please.'],
    ['أ','وَعَلَيْكُمُ السَّلامُ. تَفَضَّلْ، هَذا جَوازِي.','And peace be upon you. Here you are, this is my passport.'],
    ['م','مِنْ أَيْنَ أَنْتَ؟','Where are you from?'],
    ['أ','أَنا مِنْ بِرِيطانْيا.','I\'m from Britain.'],
    ['م','لِماذا جِئْتَ إِلى هُنا؟','Why have you come here?'],
    ['أ','جِئْتُ لِزِيارَةِ أُسْرَتِي.','I\'ve come to visit my family.'],
    ['م','كَمْ يَوْمًا تَبْقى هُنا؟','How many days are you staying?'],
    ['أ','سَأَبْقى أُسْبُوعَيْنِ.','I\'ll stay two weeks.'],
    ['م','أَهْلًا وَسَهْلًا. أَتَمَنّى لَكَ زِيارَةً طَيِّبَةً.','Welcome. I hope you have a good visit.'],
    ['أ','شُكْرًا جَزِيلًا.','Thank you very much.']]},
  {id:'doctor', pic:'🩺', en:'At the doctor', ar:'عِنْدَ الطَّبِيبِ', d:'Saying what\'s wrong and understanding advice', lines:[
    ['ط','تَفَضَّلْ، اجْلِسْ. ما بِكَ؟','Come in, sit down. What\'s wrong?'],
    ['أ','عِنْدِي صُداعٌ وَحَرارَةٌ.','I have a headache and a temperature.'],
    ['ط','مُنْذُ مَتى؟','Since when?'],
    ['أ','مُنْذُ يَوْمَيْنِ.','For two days.'],
    ['ط','هَلْ تَأْكُلُ جَيِّدًا؟','Are you eating well?'],
    ['أ','لا، لا آكُلُ كَثِيرًا.','No, I\'m not eating much.'],
    ['ط','خُذْ هَذا الدَّواءَ ثَلاثَ مَرّاتٍ فِي الْيَوْمِ.','Take this medicine three times a day.'],
    ['أ','طَيِّبٌ، شُكْرًا يا دُكْتُورُ.','Fine, thank you, doctor.'],
    ['ط','وَاشْرَبْ ماءً كَثِيرًا. سَلامَتُكَ!','And drink lots of water. Get well soon!'],
    ['أ','اللهُ يُسَلِّمُكَ.','God keep you well.']]},
  {id:'masjid', pic:'🕌', en:'At the masjid', ar:'فِي الْمَسْجِدِ', d:'A first visit: wudu, prayer times, a class', lines:[
    ['ي','السَّلامُ عَلَيْكُمْ. هَلْ أَنْتَ جَدِيدٌ فِي الْمَسْجِدِ؟','Peace be upon you. Are you new at the mosque?'],
    ['أ','وَعَلَيْكُمُ السَّلامُ. نَعَمْ، أَنا جَدِيدٌ هُنا.','And peace be upon you. Yes, I\'m new here.'],
    ['ي','أَهْلًا بِكَ! هَلْ تُرِيدُ أَنْ تَتَوَضَّأَ؟','Welcome! Do you want to do wudu?'],
    ['أ','نَعَمْ. أَيْنَ مَكانُ الْوُضُوءِ؟','Yes. Where is the wudu area?'],
    ['ي','هُناكَ، عَلَى الْيَسارِ.','Over there, on the left.'],
    ['أ','وَمَتى صَلاةُ الْعَصْرِ؟','And when is the Asr prayer?'],
    ['ي','بَعْدَ عَشْرِ دَقائِقَ.','In ten minutes.'],
    ['أ','جَزاكَ اللهُ خَيْرًا.','May God reward you.'],
    ['ي','وَإِيّاكَ. بَعْدَ الصَّلاةِ عِنْدَنا دَرْسٌ، تَعالَ مَعَنا!','And you. After the prayer we have a class — come with us!'],
    ['أ','إِنْ شاءَ اللهُ.','God willing.']]},
  {id:'restaurant', pic:'🍽️', en:'Ordering a meal', ar:'فِي الْمَطْعَمِ', d:'Ordering, asking for more, paying', lines:[
    ['ن','أَهْلًا وَسَهْلًا. ماذا تُرِيدُ أَنْ تَأْكُلَ؟','Welcome. What would you like to eat?'],
    ['أ','أُرِيدُ دَجاجًا مَعَ أَرُزٍّ، مِنْ فَضْلِكَ.','I\'d like chicken with rice, please.'],
    ['ن','وَماذا تَشْرَبُ؟','And what will you drink?'],
    ['أ','أُرِيدُ عَصِيرَ بُرْتُقالٍ.','I\'d like orange juice.'],
    ['ن','هَلْ تُرِيدُ سَلَطَةً أَيْضًا؟','Would you like a salad too?'],
    ['أ','نَعَمْ، سَلَطَةً صَغِيرَةً.','Yes, a small salad.'],
    ['ن','تَفَضَّلْ. هَلِ الطَّعامُ جَيِّدٌ؟','Here you are. Is the food good?'],
    ['أ','نَعَمْ، الطَّعامُ لَذِيذٌ جِدًّا.','Yes, the food is delicious.'],
    ['ن','الْحِسابُ خَمْسُونَ رِيالًا.','The bill is fifty riyals.'],
    ['أ','تَفَضَّلْ. شُكْرًا لَكَ.','Here you are. Thank you.']]},
  {id:'taxi', pic:'🚕', en:'Taking a taxi', ar:'فِي سَيّارَةِ الْأُجْرَةِ', d:'Where you\'re going, small talk, the fare', lines:[
    ['س','السَّلامُ عَلَيْكُمْ. إِلى أَيْنَ؟','Peace be upon you. Where to?'],
    ['أ','وَعَلَيْكُمُ السَّلامُ. إِلى الْفُنْدُقِ، مِنْ فَضْلِكَ.','And peace be upon you. To the hotel, please.'],
    ['س','أَيُّ فُنْدُقٍ؟','Which hotel?'],
    ['أ','فُنْدُقُ النُّورِ، قَرِيبٌ مِنَ السُّوقِ.','The Nur Hotel, near the market.'],
    ['س','طَيِّبٌ. هَلْ هَذِهِ أَوَّلُ زِيارَةٍ لَكَ؟','Fine. Is this your first visit?'],
    ['أ','نَعَمْ، هَذِهِ أَوَّلُ مَرَّةٍ.','Yes, this is the first time.'],
    ['س','الْمَدِينَةُ جَمِيلَةٌ. وَصَلْنا!','The city is lovely. Here we are!'],
    ['أ','بِكَمْ، مِنْ فَضْلِكَ؟','How much, please?'],
    ['س','ثَلاثُونَ رِيالًا.','Thirty riyals.'],
    ['أ','تَفَضَّلْ. مَعَ السَّلامَةِ.','Here you are. Goodbye.']]},
  {id:'family', pic:'🏠', en:'Visiting a friend\'s family', ar:'فِي زِيارَةٍ', d:'Greetings, hospitality, polite replies', lines:[
    ['ص','أَهْلًا وَسَهْلًا! تَفَضَّلْ، ادْخُلْ.','Welcome! Please come in.'],
    ['أ','شُكْرًا. بَيْتُكُمْ جَمِيلٌ.','Thank you. Your home is lovely.'],
    ['ص','هَذا أَبِي، وَهَذِهِ أُمِّي.','This is my father, and this is my mother.'],
    ['أ','تَشَرَّفْتُ بِمَعْرِفَتِكُمْ.','Pleased to meet you.'],
    ['ص','هَلْ تَشْرَبُ شايًا أَمْ قَهْوَةً؟','Would you like tea or coffee?'],
    ['أ','أُرِيدُ شايًا، مِنْ فَضْلِكَ.','Tea, please.'],
    ['ص','كَيْفَ دِراسَتُكَ؟','How are your studies going?'],
    ['أ','جَيِّدَةٌ، الْحَمْدُ لِلَّهِ. أَدْرُسُ اللُّغَةَ الْعَرَبِيَّةَ.','Well, praise God. I\'m studying Arabic.'],
    ['ص','ما شاءَ اللهُ! كَلامُكَ جَمِيلٌ.','Mashallah! You speak well.'],
    ['أ','شُكْرًا، أَتَعَلَّمُ كُلَّ يَوْمٍ.','Thank you, I\'m learning every day.']]},
];
