// Al-ʿArabiyyah Bayna Yadayk — Book 1, all 16 units + Tamhidi, 779 entries (3 duplicates removed).
// Arabic transcribed from the word lists printed at the back of both parts
// (Part 1 pp. 257-258, Part 2 pp. 259-260). English and transliteration are
// editorial additions — the book does not print them. Spot-check with a teacher.
const VOCAB = [
  { id: 1  , ar: "السَّلامُ عَلَيْكُم", en: "peace be upon you", tr: "as-salāmu ʿalaykum", unit: "1" },
  { id: 2  , ar: "وَعَلَيْكُمُ السَّلام", en: "and peace be upon you (reply)", tr: "wa-ʿalaykumu s-salām", unit: "1" },
  { id: 3  , ar: "كَيْفَ حالُكَ", en: "how are you? (to a man)", tr: "kayfa ḥāluka", unit: "1" },
  { id: 4  , ar: "كَيْفَ حالُكِ", en: "how are you? (to a woman)", tr: "kayfa ḥāluki", unit: "1" },
  { id: 5  , ar: "بِخَيْرٍ", en: "well, fine", tr: "bi-khayr", unit: "1" },
  { id: 6  , ar: "الحَمْدُ لِلَّهِ", en: "praise be to God", tr: "al-ḥamdu lillāh", unit: "1" },
  { id: 7  , ar: "أَهْلاً وَسَهْلاً", en: "welcome", tr: "ahlan wa sahlan", unit: "1" },
  { id: 8  , ar: "مَعَ السَّلامَةِ", en: "goodbye", tr: "maʿa s-salāma", unit: "1" },
  { id: 9  , ar: "ما اسْمُكَ؟", en: "what is your name? (to a man)", tr: "mā smuka", unit: "1" },
  { id: 10 , ar: "ما اسْمُكِ؟", en: "what is your name? (to a woman)", tr: "mā smuki", unit: "1" },
  { id: 11 , ar: "ما جِنْسِيَّتُكَ؟", en: "what is your nationality? (to a man)", tr: "mā jinsiyyatuka", unit: "1" },
  { id: 12 , ar: "ما جِنْسِيَّتُكِ؟", en: "what is your nationality? (to a woman)", tr: "mā jinsiyyatuki", unit: "1" },
  { id: 13 , ar: "جِنْسِيَّة", en: "nationality", tr: "jinsiyya", unit: "1" },
  { id: 14 , ar: "باكِسْتانِيّ", en: "Pakistani", tr: "bākistānī", unit: "1" },
  { id: 15 , ar: "أَنا", en: "I", tr: "anā", unit: "1" },
  { id: 16 , ar: "أَنْتَ", en: "you (m)", tr: "anta", unit: "1" },
  { id: 17 , ar: "أَنْتِ", en: "you (f)", tr: "anti", unit: "1" },
  { id: 18 , ar: "هُوَ", en: "he, it", tr: "huwa", unit: "1" },
  { id: 19 , ar: "هِيَ", en: "she, it", tr: "hiya", unit: "1" },
  { id: 20 , ar: "هَذا", en: "this (m)", tr: "hādhā", unit: "1" },
  { id: 21 , ar: "هَذِهِ", en: "this (f)", tr: "hādhihi", unit: "1" },
  { id: 22 , ar: "هَلْ؟", en: "(yes/no question marker)", tr: "hal", unit: "1" },
  { id: 23 , ar: "مَنْ؟", en: "who?", tr: "man", unit: "1" },
  { id: 24 , ar: "مِنْ أَيْنَ؟", en: "where from?", tr: "min ayna", unit: "1" },
  { id: 25 , ar: "نَعَمْ", en: "yes", tr: "naʿam", unit: "1" },
  { id: 26 , ar: "صَدِيق", en: "friend (m)", tr: "ṣadīq", unit: "1" },
  { id: 27 , ar: "صَدِيقَة", en: "friend (f)", tr: "ṣadīqa", unit: "1" },
  { id: 28 , ar: "طالِبَة", en: "student (f)", tr: "ṭāliba", unit: "1" },
  { id: 29 , ar: "طَبِيبَة", en: "doctor (f)", tr: "ṭabība", unit: "1" },
  { id: 30 , ar: "مُدَرِّس", en: "teacher (m)", tr: "mudarris", unit: "1" },
  { id: 31 , ar: "مُهَنْدِس", en: "engineer", tr: "muhandis", unit: "1" },
  { id: 32 , ar: "أَخ", en: "brother", tr: "akh", unit: "1" },
  { id: 33 , ar: "أُخْت", en: "sister", tr: "ukht", unit: "1" },
  { id: 34 , ar: "واحِد", en: "one", tr: "wāḥid", unit: "1" },
  { id: 35 , ar: "اثْنانِ", en: "two", tr: "ithnān", unit: "1" },
  { id: 36 , ar: "ثَلاثَة", en: "three", tr: "thalātha", unit: "1" },
  { id: 37 , ar: "أَرْبَعَة", en: "four", tr: "arbaʿa", unit: "1" },
  { id: 38 , ar: "خَمْسَة", en: "five", tr: "khamsa", unit: "1" },
  { id: 39 , ar: "وَ (العَطْف)", en: "and (joining words)", tr: "wa", unit: "1" },
  { id: 40 , ar: "لِ (حَرْف جَرّ)", en: "to, for (preposition)", tr: "li-", unit: "1" },
  { id: 41 , ar: "ـِي (المُتَكَلِّم)", en: "my (possessive ending)", tr: "-ī", unit: "1" },
  { id: 42 , ar: "ـِيّ (النِّسْبَة)", en: "-ish, -an (makes an adjective)", tr: "-iyy", unit: "1" },
  { id: 43 , ar: "ـِ (المُخاطَبَة)", en: "you (f) verb ending", tr: "-ī", unit: "1" },
  { id: 44 , ar: "ـكَ (المُخاطَب)", en: "your (m)", tr: "-ka", unit: "1" },
  { id: 45 , ar: "ـكِ (المُخاطَبَة)", en: "your (f)", tr: "-ki", unit: "1" },
  { id: 46 , ar: "أَب", en: "father", tr: "ab", unit: "2" },
  { id: 47 , ar: "ابْن", en: "son", tr: "ibn", unit: "2" },
  { id: 48 , ar: "ابْنَة", en: "daughter", tr: "ibna", unit: "2" },
  { id: 49 , ar: "أُسْرَة", en: "family", tr: "usra", unit: "2" },
  { id: 50 , ar: "أُمّ", en: "mother", tr: "umm", unit: "2" },
  { id: 51 , ar: "أَوْلاد", en: "children, boys", tr: "awlād", unit: "2" },
  { id: 52 , ar: "جَدّ", en: "grandfather", tr: "jadd", unit: "2" },
  { id: 53 , ar: "جَدَّة", en: "grandmother", tr: "jadda", unit: "2" },
  { id: 54 , ar: "عَمّ", en: "paternal uncle", tr: "ʿamm", unit: "2" },
  { id: 55 , ar: "عَمَّة", en: "paternal aunt", tr: "ʿamma", unit: "2" },
  { id: 56 , ar: "والِد", en: "father", tr: "wālid", unit: "2" },
  { id: 57 , ar: "والِدَة", en: "mother", tr: "wālida", unit: "2" },
  { id: 58 , ar: "طالِب", en: "student (m)", tr: "ṭālib", unit: "2" },
  { id: 59 , ar: "مُعَلِّمَة", en: "teacher (f)", tr: "muʿallima", unit: "2" },
  { id: 60 , ar: "أَذان", en: "call to prayer", tr: "adhān", unit: "2" },
  { id: 61 , ar: "الفَجْر", en: "dawn; the dawn prayer", tr: "al-fajr", unit: "2" },
  { id: 62 , ar: "مَسْجِد", en: "mosque", tr: "masjid", unit: "2" },
  { id: 63 , ar: "مُصَلَّى", en: "prayer room", tr: "muṣallā", unit: "2" },
  { id: 64 , ar: "صَلَّى / يُصَلِّي", en: "to pray", tr: "ṣallā / yuṣallī", unit: "2" },
  { id: 65 , ar: "تَوَضَّأَ / يَتَوَضَّأُ", en: "to perform wudu", tr: "tawaḍḍaʾa / yatawaḍḍaʾu", unit: "2" },
  { id: 66 , ar: "قَرَأَ / يَقْرَأُ", en: "to read", tr: "qaraʾa / yaqraʾu", unit: "2" },
  { id: 67 , ar: "القُرْآن", en: "the Qur'an", tr: "al-qurʾān", unit: "2" },
  { id: 68 , ar: "الرَّسُول", en: "the Messenger", tr: "ar-rasūl", unit: "2" },
  { id: 69 , ar: "صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ", en: "peace and blessings be upon him", tr: "ṣallā llāhu ʿalayhi wa-sallam", unit: "2" },
  { id: 70 , ar: "اللهُ أَكْبَرُ", en: "God is greatest", tr: "allāhu akbar", unit: "2" },
  { id: 71 , ar: "ما شاءَ اللهُ", en: "what God has willed", tr: "mā shāʾa llāh", unit: "2" },
  { id: 72 , ar: "هَيَّا بِنا", en: "let's go", tr: "hayyā binā", unit: "2" },
  { id: 73 , ar: "صُورَة", en: "picture, photo", tr: "ṣūra", unit: "2" },
  { id: 74 , ar: "شَجَرَة", en: "tree", tr: "shajara", unit: "2" },
  { id: 75 , ar: "غُرْفَة", en: "room", tr: "ghurfa", unit: "2" },
  { id: 76 , ar: "حَمَّام", en: "bathroom", tr: "ḥammām", unit: "2" },
  { id: 77 , ar: "نَظَّارَة", en: "glasses", tr: "naẓẓāra", unit: "2" },
  { id: 78 , ar: "مِعْطَف", en: "coat", tr: "miʿṭaf", unit: "2" },
  { id: 79 , ar: "سَبْعَة", en: "seven", tr: "sabʿa", unit: "2" },
  { id: 80 , ar: "ثَمانِيَة", en: "eight", tr: "thamāniya", unit: "2" },
  { id: 81 , ar: "تِسْعَة", en: "nine", tr: "tisʿa", unit: "2" },
  { id: 82 , ar: "عَشَرَة", en: "ten", tr: "ʿashara", unit: "2" },
  { id: 83 , ar: "سَنَة", en: "year", tr: "sana", unit: "2" },
  { id: 84 , ar: "إِلى", en: "to, towards", tr: "ilā", unit: "2" },
  { id: 85 , ar: "فِي", en: "in", tr: "fī", unit: "2" },
  { id: 86 , ar: "أَيْنَ", en: "where", tr: "ayna", unit: "2" },
  { id: 87 , ar: "يا (النِّداء)", en: "O (used before a name)", tr: "yā", unit: "2" },
  { id: 88 , ar: "ـهُ (هاء الغائب)", en: "his, him", tr: "-hu", unit: "2" },
  { id: 89 , ar: "ـها (هاء الغائبة)", en: "her", tr: "-hā", unit: "2" },
  { id: 90 , ar: "بَيْت", en: "house", tr: "bayt", unit: "3" },
  { id: 91 , ar: "شَقَّة", en: "flat, apartment", tr: "shaqqa", unit: "3" },
  { id: 92 , ar: "غُرَف", en: "rooms", tr: "ghuraf", unit: "3" },
  { id: 93 , ar: "غُرْفَة نَوْم", en: "bedroom", tr: "ghurfat nawm", unit: "3" },
  { id: 94 , ar: "غُرْفَة جُلُوس", en: "sitting room", tr: "ghurfat julūs", unit: "3" },
  { id: 95 , ar: "سَرِير", en: "bed", tr: "sarīr", unit: "3" },
  { id: 96 , ar: "سِتارَة", en: "curtain", tr: "sitāra", unit: "3" },
  { id: 97 , ar: "سَجَّادَة", en: "rug, carpet", tr: "sajjāda", unit: "3" },
  { id: 98 , ar: "سَخَّان", en: "water heater", tr: "sakhkhān", unit: "3" },
  { id: 99 , ar: "فُرْن", en: "oven", tr: "furn", unit: "3" },
  { id: 100, ar: "ثَلَّاجَة", en: "fridge", tr: "thallāja", unit: "3" },
  { id: 101, ar: "مِرْآة", en: "mirror", tr: "mirʾāh", unit: "3" },
  { id: 102, ar: "دَوْر", en: "floor, storey", tr: "dawr", unit: "3" },
  { id: 103, ar: "رَقْم", en: "number", tr: "raqm", unit: "3" },
  { id: 104, ar: "حَيّ", en: "district, neighbourhood", tr: "ḥayy", unit: "3" },
  { id: 105, ar: "جامِعَة", en: "university", tr: "jāmiʿa", unit: "3" },
  { id: 106, ar: "سَكَنَ / يَسْكُنُ", en: "to live, reside", tr: "sakana / yaskunu", unit: "3" },
  { id: 107, ar: "دَخَلَ / يَدْخُلُ", en: "to enter", tr: "dakhala / yadkhulu", unit: "3" },
  { id: 108, ar: "تَفَضَّلْ (ادْخُلْ)", en: "please, come in", tr: "tafaḍḍal (udkhul)", unit: "3" },
  { id: 109, ar: "مِنْ فَضْلِكَ", en: "please", tr: "min faḍlika", unit: "3" },
  { id: 110, ar: "شُكْراً", en: "thank you", tr: "shukran", unit: "3" },
  { id: 111, ar: "لَدَى", en: "to have; at", tr: "ladā", unit: "3" },
  { id: 112, ar: "مُؤَجِّر", en: "landlord", tr: "muʾajjir", unit: "3" },
  { id: 113, ar: "مُسْتَأْجِر", en: "tenant", tr: "mustaʾjir", unit: "3" },
  { id: 114, ar: "مُشْتَرٍ", en: "buyer", tr: "mushtarin", unit: "3" },
  { id: 115, ar: "مُشاهَدَة", en: "watching, viewing", tr: "mushāhada", unit: "3" },
  { id: 116, ar: "كَمْ؟", en: "how many?", tr: "kam", unit: "3" },
  { id: 117, ar: "فِي أَيِّ؟", en: "in which?", tr: "fī ayyi", unit: "3" },
  { id: 118, ar: "ماذا؟", en: "what?", tr: "mādhā", unit: "3" },
  { id: 119, ar: "السَّبْت", en: "Saturday", tr: "as-sabt", unit: "3" },
  { id: 120, ar: "الثُّلاثاء", en: "Tuesday", tr: "ath-thulāthāʾ", unit: "3" },
  { id: 121, ar: "الخَمِيس", en: "Thursday", tr: "al-khamīs", unit: "3" },
  { id: 122, ar: "الجُمُعَة", en: "Friday", tr: "al-jumuʿa", unit: "3" },
  { id: 123, ar: "خامِس", en: "fifth", tr: "khāmis", unit: "3" },
  { id: 124, ar: "خَمْس", en: "five (with fem. nouns)", tr: "khams", unit: "3" },
  { id: 125, ar: "جَمِيلَة", en: "beautiful (f)", tr: "jamīla", unit: "3" },
  { id: 126, ar: "شَيْء", en: "thing", tr: "shayʾ", unit: "3" },
  { id: 127, ar: "ما (النافية)", en: "not (negates the past)", tr: "mā", unit: "3" },
  { id: 128, ar: "لا (الجوابية)", en: "no (in answer)", tr: "lā", unit: "3" },
  { id: 129, ar: "اسْتَيْقَظَ / يَسْتَيْقِظُ", en: "to wake up", tr: "istayqaẓa / yastayqiẓu", unit: "4" },
  { id: 130, ar: "نامَ / يَنامُ", en: "to sleep", tr: "nāma / yanāmu", unit: "4" },
  { id: 131, ar: "ذَهَبَ / يَذْهَبُ", en: "to go", tr: "dhahaba / yadhhabu", unit: "4" },
  { id: 132, ar: "غَسَلَ / يَغْسِلُ", en: "to wash", tr: "ghasala / yaghsilu", unit: "4" },
  { id: 133, ar: "كَنَسَ / يَكْنُسُ", en: "to sweep", tr: "kanasa / yaknusu", unit: "4" },
  { id: 134, ar: "كَوَى / يَكْوِي", en: "to iron", tr: "kawā / yakwī", unit: "4" },
  { id: 135, ar: "شاهَدَ / يُشاهِدُ", en: "to watch", tr: "shāhada / yushāhidu", unit: "4" },
  { id: 136, ar: "فَعَلَ / يَفْعَلُ", en: "to do", tr: "faʿala / yafʿalu", unit: "4" },
  { id: 137, ar: "السَّاعَة", en: "the hour, o'clock; watch", tr: "as-sāʿa", unit: "4" },
  { id: 138, ar: "السَّابِعَة", en: "the seventh; seven o'clock", tr: "as-sābiʿa", unit: "4" },
  { id: 139, ar: "صَباح", en: "morning", tr: "ṣabāḥ", unit: "4" },
  { id: 140, ar: "مُبَكِّراً", en: "early", tr: "mubakkiran", unit: "4" },
  { id: 141, ar: "مُتَأَخِّراً", en: "late", tr: "mutaʾakhkhiran", unit: "4" },
  { id: 142, ar: "مَتى", en: "when", tr: "matā", unit: "4" },
  { id: 143, ar: "حافِلَة", en: "bus", tr: "ḥāfila", unit: "4" },
  { id: 144, ar: "سَيَّارَة", en: "car", tr: "sayyāra", unit: "4" },
  { id: 145, ar: "تِلْفاز", en: "television", tr: "tilfāz", unit: "4" },
  { id: 146, ar: "صَحِيفَة", en: "newspaper", tr: "ṣaḥīfa", unit: "4" },
  { id: 147, ar: "مَلابِس", en: "clothes", tr: "malābis", unit: "4" },
  { id: 148, ar: "أَطْباق", en: "dishes, plates", tr: "aṭbāq", unit: "4" },
  { id: 149, ar: "مَدْرَسَة", en: "school", tr: "madrasa", unit: "4" },
  { id: 150, ar: "كِتاب", en: "book", tr: "kitāb", unit: "4" },
  { id: 151, ar: "الصَّلاة", en: "prayer", tr: "aṣ-ṣalāh", unit: "4" },
  { id: 152, ar: "يَوْم عُطْلَة", en: "day off", tr: "yawm ʿuṭla", unit: "4" },
  { id: 153, ar: "يَوْم عَمَل", en: "working day", tr: "yawm ʿamal", unit: "4" },
  { id: 154, ar: "أَوَّل", en: "first", tr: "awwal", unit: "4" },
  { id: 155, ar: "ثانٍ", en: "second", tr: "thānin", unit: "4" },
  { id: 156, ar: "ثالِث", en: "third", tr: "thālith", unit: "4" },
  { id: 157, ar: "رابِع", en: "fourth", tr: "rābiʿ", unit: "4" },
  { id: 158, ar: "بَعْدَ", en: "after", tr: "baʿda", unit: "4" },
  { id: 159, ar: "أَوْ", en: "or", tr: "aw", unit: "4" },
  { id: 160, ar: "أَيْضاً", en: "also, too", tr: "ayḍan", unit: "4" },
  { id: 161, ar: "كَبِير", en: "big, large", tr: "kabīr", unit: "4" },
  { id: 162, ar: "بِ (حَرْف جَرّ)", en: "by, with (preposition)", tr: "bi-", unit: "4" },
  { id: 163, ar: "لا (النافية)", en: "not (negates the present)", tr: "lā", unit: "4" },
  { id: 164, ar: "أَرُزّ", en: "rice", tr: "aruzz", unit: "5" },
  { id: 165, ar: "أَكَلَ / يَأْكُلُ", en: "to eat", tr: "akala / yaʾkulu", unit: "5" },
  { id: 166, ar: "تَمْر", en: "dates", tr: "tamr", unit: "5" },
  { id: 167, ar: "جَوْعانُ", en: "hungry", tr: "jawʿān", unit: "5" },
  { id: 168, ar: "حَلِيب", en: "milk", tr: "ḥalīb", unit: "5" },
  { id: 169, ar: "خُبْز", en: "bread", tr: "khubz", unit: "5" },
  { id: 170, ar: "دَجاج", en: "chicken", tr: "dajāj", unit: "5" },
  { id: 171, ar: "سَلَطَة", en: "salad", tr: "salaṭa", unit: "5" },
  { id: 172, ar: "سَمَك", en: "fish", tr: "samak", unit: "5" },
  { id: 173, ar: "سَمِين", en: "fat, overweight", tr: "samīn", unit: "5" },
  { id: 174, ar: "نَحِيف", en: "thin, slim", tr: "naḥīf", unit: "5" },
  { id: 175, ar: "شاي", en: "tea", tr: "shāy", unit: "5" },
  { id: 176, ar: "شَراب", en: "drink", tr: "sharāb", unit: "5" },
  { id: 177, ar: "شَرِبَ / يَشْرَبُ", en: "to drink", tr: "shariba / yashrabu", unit: "5" },
  { id: 178, ar: "ضُيُوف", en: "guests", tr: "ḍuyūf", unit: "5" },
  { id: 179, ar: "طَعام", en: "food", tr: "ṭaʿām", unit: "5" },
  { id: 180, ar: "طَلَبَ / يَطْلُبُ", en: "to order, request", tr: "ṭalaba / yaṭlubu", unit: "5" },
  { id: 181, ar: "عَشاء", en: "dinner", tr: "ʿashāʾ", unit: "5" },
  { id: 182, ar: "غَداء", en: "lunch", tr: "ghadāʾ", unit: "5" },
  { id: 183, ar: "فُطُور", en: "breakfast", tr: "fuṭūr", unit: "5" },
  { id: 184, ar: "عَفْواً", en: "you're welcome; excuse me", tr: "ʿafwan", unit: "5" },
  { id: 185, ar: "عَلى", en: "on, over", tr: "ʿalā", unit: "5" },
  { id: 186, ar: "عِنَب", en: "grapes", tr: "ʿinab", unit: "5" },
  { id: 187, ar: "فاكِهَة", en: "fruit", tr: "fākiha", unit: "5" },
  { id: 188, ar: "فَضَّلَ / يُفَضِّلُ", en: "to prefer", tr: "faḍḍala / yufaḍḍilu", unit: "5" },
  { id: 189, ar: "قَلِيل", en: "little, few", tr: "qalīl", unit: "5" },
  { id: 190, ar: "قَهْوَة", en: "coffee", tr: "qahwa", unit: "5" },
  { id: 191, ar: "كَثِير", en: "much, many", tr: "kathīr", unit: "5" },
  { id: 192, ar: "كِيلُو", en: "kilo", tr: "kīlū", unit: "5" },
  { id: 193, ar: "لَحْم", en: "meat", tr: "laḥm", unit: "5" },
  { id: 194, ar: "ماء", en: "water", tr: "māʾ", unit: "5" },
  { id: 195, ar: "مائِدَة", en: "dining table", tr: "māʾida", unit: "5" },
  { id: 196, ar: "مَطْعَم", en: "restaurant", tr: "maṭʿam", unit: "5" },
  { id: 197, ar: "مُسافِرَة", en: "traveller (f)", tr: "musāfira", unit: "5" },
  { id: 198, ar: "مُضِيفَة", en: "hostess, air stewardess", tr: "muḍīfa", unit: "5" },
  { id: 199, ar: "وَجْبَة", en: "meal", tr: "wajba", unit: "5" },
  { id: 200, ar: "وَجَبات", en: "meals", tr: "wajabāt", unit: "5" },
  { id: 201, ar: "وَزْن", en: "weight", tr: "wazn", unit: "5" },
  { id: 202, ar: "مِائَة", en: "hundred", tr: "miʾa", unit: "5" },
  { id: 203, ar: "لِماذا", en: "why", tr: "limādhā", unit: "5" },
  { id: 204, ar: "جَلَسَ / يَجْلِسُ", en: "to sit", tr: "jalasa / yajlisu", unit: "5" },
  { id: 205, ar: "جِدّاً", en: "very", tr: "jiddan", unit: "5" },
  { id: 206, ar: "أُولى", en: "first (f)", tr: "ūlā", unit: "5" },
  { id: 207, ar: "ثانِيَة", en: "second (f)", tr: "thāniya", unit: "5" },
  { id: 208, ar: "ثالِثَة", en: "third (f)", tr: "thālitha", unit: "5" },
  { id: 209, ar: "رابِعَة", en: "fourth (f)", tr: "rābiʿa", unit: "5" },
  { id: 210, ar: "خامِسَة", en: "fifth (f)", tr: "khāmisa", unit: "5" },
  { id: 211, ar: "ثَلاث", en: "three (with fem. nouns)", tr: "thalāth", unit: "5" },
  { id: 212, ar: "واحِدَة", en: "one (f)", tr: "wāḥida", unit: "5" },
  { id: 213, ar: "لا (الناهية)", en: "don't (prohibition)", tr: "lā", unit: "5" },
  { id: 214, ar: "الظُّهْر", en: "noon; the midday prayer", tr: "aẓ-ẓuhr", unit: "6" },
  { id: 215, ar: "العَصْر", en: "afternoon; the afternoon prayer", tr: "al-ʿaṣr", unit: "6" },
  { id: 216, ar: "المَغْرِب", en: "sunset; the sunset prayer", tr: "al-maghrib", unit: "6" },
  { id: 217, ar: "العِشاء", en: "nightfall; the night prayer", tr: "al-ʿishāʾ", unit: "6" },
  { id: 218, ar: "صَلَوات", en: "prayers", tr: "ṣalawāt", unit: "6" },
  { id: 219, ar: "مَكَّة", en: "Mecca", tr: "makka", unit: "6" },
  { id: 220, ar: "المَدِينَة (المُنَوَّرَة)", en: "Medina", tr: "al-madīna (al-munawwara)", unit: "6" },
  { id: 221, ar: "المَسْجِد الحَرام", en: "the Sacred Mosque", tr: "al-masjid al-ḥarām", unit: "6" },
  { id: 222, ar: "المَسْجِد النَّبَوِيّ", en: "the Prophet's Mosque", tr: "al-masjid an-nabawī", unit: "6" },
  { id: 223, ar: "طائِرَة", en: "aeroplane", tr: "ṭāʾira", unit: "6" },
  { id: 224, ar: "ذاهِب", en: "going", tr: "dhāhib", unit: "6" },
  { id: 225, ar: "إِلى أَيْنَ", en: "where to", tr: "ilā ayna", unit: "6" },
  { id: 226, ar: "انْتَظَرَ / يَنْتَظِرُ", en: "to wait", tr: "intaẓara / yantaẓiru", unit: "6" },
  { id: 227, ar: "سَمِعَ / يَسْمَعُ", en: "to hear", tr: "samiʿa / yasmaʿu", unit: "6" },
  { id: 228, ar: "وَضَعَ / يَضَعُ", en: "to put, place", tr: "waḍaʿa / yaḍaʿu", unit: "6" },
  { id: 229, ar: "عَمِلَ / يَعْمَلُ", en: "to work", tr: "ʿamila / yaʿmalu", unit: "6" },
  { id: 230, ar: "اسْتَطاعَ / يَسْتَطِيعُ", en: "to be able to", tr: "istaṭāʿa / yastaṭīʿu", unit: "6" },
  { id: 231, ar: "آسِف", en: "sorry", tr: "āsif", unit: "6" },
  { id: 232, ar: "أَفْضَل", en: "better, best", tr: "afḍal", unit: "6" },
  { id: 233, ar: "إِنْ شاءَ اللهُ", en: "God willing", tr: "in shāʾa llāh", unit: "6" },
  { id: 234, ar: "جَزاكَ اللهُ خَيْراً", en: "may God reward you", tr: "jazāka llāhu khayran", unit: "6" },
  { id: 235, ar: "فِكْرَة طَيِّبَة", en: "a good idea", tr: "fikra ṭayyiba", unit: "6" },
  { id: 236, ar: "صَحِيح", en: "correct, true", tr: "ṣaḥīḥ", unit: "6" },
  { id: 237, ar: "قَرِيب", en: "near", tr: "qarīb", unit: "6" },
  { id: 238, ar: "بَعِيد", en: "far", tr: "baʿīd", unit: "6" },
  { id: 239, ar: "بِجانِبِ", en: "next to, beside", tr: "bi-jānibi", unit: "6" },
  { id: 240, ar: "كَسْلانُ", en: "lazy", tr: "kaslān", unit: "6" },
  { id: 241, ar: "مَرِيض", en: "ill, sick", tr: "marīḍ", unit: "6" },
  { id: 242, ar: "مُنَبِّه", en: "alarm clock", tr: "munabbih", unit: "6" },
  { id: 243, ar: "لَيْل", en: "night", tr: "layl", unit: "6" },
  { id: 244, ar: "مَعَ", en: "with", tr: "maʿa", unit: "6" },
  { id: 245, ar: "لِ (التَّعْلِيل)", en: "in order to, for", tr: "li-", unit: "6" },
  { id: 246, ar: "سادِس", en: "sixth", tr: "sādis", unit: "6" },
  { id: 247, ar: "سابِع", en: "seventh", tr: "sābiʿ", unit: "6" },
  { id: 248, ar: "ثامِن", en: "eighth", tr: "thāmin", unit: "6" },
  { id: 249, ar: "تاسِع", en: "ninth", tr: "tāsiʿ", unit: "6" },
  { id: 250, ar: "عاشِر", en: "tenth", tr: "ʿāshir", unit: "6" },
  { id: 251, ar: "اخْتِبار", en: "test, exam", tr: "ikhtibār", unit: "7" },
  { id: 252, ar: "أُسْبُوع", en: "week", tr: "usbūʿ", unit: "7" },
  { id: 253, ar: "أَشْهُر", en: "months", tr: "ashhur", unit: "7" },
  { id: 254, ar: "الآنَ", en: "now", tr: "al-ān", unit: "7" },
  { id: 255, ar: "انْتَهى / يَنْتَهِي", en: "to finish, end", tr: "intahā / yantahī", unit: "7" },
  { id: 256, ar: "بَدَأَ / يَبْدَأُ", en: "to begin", tr: "badaʾa / yabdaʾu", unit: "7" },
  { id: 257, ar: "تارِيخ", en: "history; date", tr: "tārīkh", unit: "7" },
  { id: 258, ar: "ثَقافَة إِسْلامِيَّة", en: "Islamic culture", tr: "thaqāfa islāmiyya", unit: "7" },
  { id: 259, ar: "جاءَ / يَجِيءُ", en: "to come", tr: "jāʾa / yajīʾu", unit: "7" },
  { id: 260, ar: "جَدْوَل دِراسِيّ", en: "timetable", tr: "jadwal dirāsī", unit: "7" },
  { id: 261, ar: "حاسُوب", en: "computer", tr: "ḥāsūb", unit: "7" },
  { id: 262, ar: "حِصَّة", en: "class period, lesson", tr: "ḥiṣṣa", unit: "7" },
  { id: 263, ar: "حِصَص", en: "class periods", tr: "ḥiṣaṣ", unit: "7" },
  { id: 264, ar: "دِراسَة", en: "study", tr: "dirāsa", unit: "7" },
  { id: 265, ar: "دَرَسَ / يَدْرُسُ", en: "to study", tr: "darasa / yadrusu", unit: "7" },
  { id: 266, ar: "رِياضِيَّات", en: "mathematics", tr: "riyāḍiyyāt", unit: "7" },
  { id: 267, ar: "صَفّ دِراسِيّ", en: "classroom, class", tr: "ṣaff dirāsī", unit: "7" },
  { id: 268, ar: "عُطْلَة", en: "holiday", tr: "ʿuṭla", unit: "7" },
  { id: 269, ar: "عُلُوم", en: "science", tr: "ʿulūm", unit: "7" },
  { id: 270, ar: "كانَ / يَكُونُ", en: "to be", tr: "kāna / yakūnu", unit: "7" },
  { id: 271, ar: "كَتَبَ / يَكْتُبُ", en: "to write", tr: "kataba / yaktubu", unit: "7" },
  { id: 272, ar: "كُلِّيَّة", en: "college, faculty", tr: "kulliyya", unit: "7" },
  { id: 273, ar: "كُلِّيَّة التَّرْبِيَة", en: "College of Education", tr: "kulliyyat at-tarbiya", unit: "7" },
  { id: 274, ar: "كُلِّيَّة الطِّبّ", en: "College of Medicine", tr: "kulliyyat aṭ-ṭibb", unit: "7" },
  { id: 275, ar: "لُغَة عَرَبِيَّة", en: "Arabic language", tr: "lugha ʿarabiyya", unit: "7" },
  { id: 276, ar: "لَوْحَة", en: "board; painting", tr: "lawḥa", unit: "7" },
  { id: 277, ar: "مُخْتَبَر", en: "laboratory", tr: "mukhtabar", unit: "7" },
  { id: 278, ar: "مُعَلِّم", en: "teacher (m)", tr: "muʿallim", unit: "7" },
  { id: 279, ar: "مَكْتَبَة", en: "library", tr: "maktaba", unit: "7" },
  { id: 280, ar: "مَوادّ دِراسِيَّة", en: "school subjects", tr: "mawādd dirāsiyya", unit: "7" },
  { id: 281, ar: "نَظَرَ / يَنْظُرُ", en: "to look", tr: "naẓara / yanẓuru", unit: "7" },
  { id: 282, ar: "وَقْت", en: "time", tr: "waqt", unit: "7" },
  { id: 283, ar: "يَوْم دِراسِيّ", en: "school day", tr: "yawm dirāsī", unit: "7" },
  { id: 284, ar: "أَحَبَّ / يُحِبُّ", en: "to love, like", tr: "aḥabba / yuḥibbu", unit: "8" },
  { id: 285, ar: "أَطْفال", en: "children", tr: "aṭfāl", unit: "8" },
  { id: 286, ar: "طِفْل", en: "child", tr: "ṭifl", unit: "8" },
  { id: 287, ar: "تَمْرِيض", en: "nursing", tr: "tamrīḍ", unit: "8" },
  { id: 288, ar: "مُمَرِّض", en: "nurse (m)", tr: "mumarriḍ", unit: "8" },
  { id: 289, ar: "حادِيَة عَشْرَة", en: "eleventh (f); eleven o'clock", tr: "ḥādiya ʿashra", unit: "8" },
  { id: 290, ar: "دَرَّسَ / يُدَرِّسُ", en: "to teach", tr: "darrasa / yudarrisu", unit: "8" },
  { id: 291, ar: "ساعات", en: "hours", tr: "sāʿāt", unit: "8" },
  { id: 292, ar: "ساعَة (آلة)", en: "clock, watch", tr: "sāʿa", unit: "8" },
  { id: 293, ar: "ساعَة (وَقْت)", en: "hour", tr: "sāʿa", unit: "8" },
  { id: 294, ar: "شَرِكَة", en: "company", tr: "sharika", unit: "8" },
  { id: 295, ar: "صَيْدَلَة", en: "pharmacy (the subject)", tr: "ṣaydala", unit: "8" },
  { id: 296, ar: "صَيْدَلِيّ", en: "pharmacist", tr: "ṣaydalī", unit: "8" },
  { id: 297, ar: "طِبّ", en: "medicine (the subject)", tr: "ṭibb", unit: "8" },
  { id: 298, ar: "طَبِيب", en: "doctor (m)", tr: "ṭabīb", unit: "8" },
  { id: 299, ar: "طُلَّاب", en: "students", tr: "ṭullāb", unit: "8" },
  { id: 300, ar: "طَيَّار", en: "pilot", tr: "ṭayyār", unit: "8" },
  { id: 301, ar: "طَيَران", en: "aviation, flying", tr: "ṭayarān", unit: "8" },
  { id: 302, ar: "عَمَل", en: "work", tr: "ʿamal", unit: "8" },
  { id: 303, ar: "كُلِّيَّة التَّمْرِيض", en: "College of Nursing", tr: "kulliyyat at-tamrīḍ", unit: "8" },
  { id: 304, ar: "كُلِّيَّة الصَّيْدَلَة", en: "College of Pharmacy", tr: "kulliyyat aṣ-ṣaydala", unit: "8" },
  { id: 305, ar: "كُلِّيَّة الطَّيَران", en: "College of Aviation", tr: "kulliyyat aṭ-ṭayarān", unit: "8" },
  { id: 306, ar: "كُلِّيَّة الهَنْدَسَة", en: "College of Engineering", tr: "kulliyyat al-handasa", unit: "8" },
  { id: 307, ar: "مَرْحَلَة", en: "stage, level", tr: "marḥala", unit: "8" },
  { id: 308, ar: "مَرْحَلَة ابْتِدائِيَّة", en: "primary stage", tr: "marḥala ibtidāʾiyya", unit: "8" },
  { id: 309, ar: "مَرْحَلَة مُتَوَسِّطَة", en: "intermediate stage", tr: "marḥala mutawassiṭa", unit: "8" },
  { id: 310, ar: "مُسْتَشْفى", en: "hospital", tr: "mustashfā", unit: "8" },
  { id: 311, ar: "مِهْنَة", en: "profession", tr: "mihna", unit: "8" },
  { id: 312, ar: "هَنْدَسَة", en: "engineering", tr: "handasa", unit: "8" },
  { id: 313, ar: "أَبْيَضُ", en: "white", tr: "abyaḍ", unit: "9" },
  { id: 314, ar: "أَثْواب", en: "robes, garments", tr: "athwāb", unit: "9" },
  { id: 315, ar: "أَحْمَرُ", en: "red", tr: "aḥmar", unit: "9" },
  { id: 316, ar: "أَخْضَرُ", en: "green", tr: "akhḍar", unit: "9" },
  { id: 317, ar: "أَزْرَقُ", en: "blue", tr: "azraq", unit: "9" },
  { id: 318, ar: "أَسْوَدُ", en: "black", tr: "aswad", unit: "9" },
  { id: 319, ar: "اشْتَرى / يَشْتَرِي", en: "to buy", tr: "ishtarā / yashtarī", unit: "9" },
  { id: 320, ar: "أَصْفَرُ", en: "yellow", tr: "aṣfar", unit: "9" },
  { id: 321, ar: "بَصَل", en: "onions", tr: "baṣal", unit: "9" },
  { id: 322, ar: "بَيْض", en: "eggs", tr: "bayḍ", unit: "9" },
  { id: 323, ar: "ثَلاثُونَ", en: "thirty", tr: "thalāthūn", unit: "9" },
  { id: 324, ar: "ثَمانُونَ", en: "eighty", tr: "thamānūn", unit: "9" },
  { id: 325, ar: "ثَوْب", en: "robe, thobe", tr: "thawb", unit: "9" },
  { id: 326, ar: "خَمْسُونَ", en: "fifty", tr: "khamsūn", unit: "9" },
  { id: 327, ar: "خِيار", en: "cucumber", tr: "khiyār", unit: "9" },
  { id: 328, ar: "دَفْتَر", en: "notebook", tr: "daftar", unit: "9" },
  { id: 329, ar: "دِينار", en: "dinar", tr: "dīnār", unit: "9" },
  { id: 330, ar: "رِيال", en: "riyal", tr: "riyāl", unit: "9" },
  { id: 331, ar: "سُكَّر", en: "sugar", tr: "sukkar", unit: "9" },
  { id: 332, ar: "طَبَق بَيْض", en: "tray of eggs", tr: "ṭabaq bayḍ", unit: "9" },
  { id: 333, ar: "طَماطِم", en: "tomatoes", tr: "ṭamāṭim", unit: "9" },
  { id: 334, ar: "عُلْبَة مِلْح", en: "packet of salt", tr: "ʿulbat milḥ", unit: "9" },
  { id: 335, ar: "قِسْم", en: "section, department", tr: "qism", unit: "9" },
  { id: 336, ar: "قُمْصان", en: "shirts", tr: "qumṣān", unit: "9" },
  { id: 337, ar: "قَمِيص", en: "shirt", tr: "qamīṣ", unit: "9" },
  { id: 338, ar: "كِتاب قِراءَة", en: "reading book", tr: "kitāb qirāʾa", unit: "9" },
  { id: 339, ar: "كِتاب قَواعِد", en: "grammar book", tr: "kitāb qawāʿid", unit: "9" },
  { id: 340, ar: "لَوْ سَمَحْتَ", en: "excuse me, please", tr: "law samaḥta", unit: "9" },
  { id: 341, ar: "امْرَأَة", en: "woman", tr: "imraʾa", unit: "9" },
  { id: 342, ar: "المَطْلُوب", en: "the amount due, the total", tr: "al-maṭlūb", unit: "9" },
  { id: 343, ar: "مُعْجَم", en: "dictionary", tr: "muʿjam", unit: "9" },
  { id: 344, ar: "مُعْجَم عَرَبِيّ", en: "Arabic dictionary", tr: "muʿjam ʿarabī", unit: "9" },
  { id: 345, ar: "مِلْح", en: "salt", tr: "milḥ", unit: "9" },
  { id: 346, ar: "هُنا", en: "here", tr: "hunā", unit: "9" },
  { id: 347, ar: "اخْضَرَّ / يَخْضَرُّ", en: "to turn green", tr: "ikhḍarra / yakhḍarru", unit: "10" },
  { id: 348, ar: "أَمامَ", en: "in front of", tr: "amāma", unit: "10" },
  { id: 349, ar: "أَمْطَرَ / تُمْطِرُ", en: "to rain", tr: "amṭara / tumṭiru", unit: "10" },
  { id: 350, ar: "بارِد", en: "cold", tr: "bārid", unit: "10" },
  { id: 351, ar: "بارَكَ اللهُ فِيكَ", en: "God bless you", tr: "bāraka llāhu fīka", unit: "10" },
  { id: 352, ar: "البَرّ", en: "open country, desert", tr: "al-barr", unit: "10" },
  { id: 353, ar: "بَرْد", en: "cold (the cold)", tr: "bard", unit: "10" },
  { id: 354, ar: "بَقِيَ / يَبْقى", en: "to stay, remain", tr: "baqiya / yabqā", unit: "10" },
  { id: 355, ar: "تَحْتَ", en: "under, below", tr: "taḥta", unit: "10" },
  { id: 356, ar: "تَحْتَ الصِّفْرِ", en: "below zero", tr: "taḥta ṣ-ṣifr", unit: "10" },
  { id: 357, ar: "تَرَكَ / يَتْرُكُ", en: "to leave", tr: "taraka / yatruku", unit: "10" },
  { id: 358, ar: "تَكَلَّمَ / يَتَكَلَّمُ", en: "to speak", tr: "takallama / yatakallamu", unit: "10" },
  { id: 359, ar: "الجَوّ (الطَّقْس)", en: "the weather", tr: "al-jaww (aṭ-ṭaqs)", unit: "10" },
  { id: 360, ar: "حارّ", en: "hot", tr: "ḥārr", unit: "10" },
  { id: 361, ar: "حَرّ", en: "heat", tr: "ḥarr", unit: "10" },
  { id: 362, ar: "حَضَرَ / يَحْضُرُ", en: "to come, attend", tr: "ḥaḍara / yaḥḍuru", unit: "10" },
  { id: 363, ar: "خارِجَ", en: "outside", tr: "khārija", unit: "10" },
  { id: 364, ar: "خَلْفَ", en: "behind", tr: "khalfa", unit: "10" },
  { id: 365, ar: "خَيْمَة", en: "tent", tr: "khayma", unit: "10" },
  { id: 366, ar: "دافِئ", en: "warm", tr: "dāfiʾ", unit: "10" },
  { id: 367, ar: "دَرَجَة الحَرارَة", en: "temperature", tr: "darajat al-ḥarāra", unit: "10" },
  { id: 368, ar: "سَماء", en: "sky", tr: "samāʾ", unit: "10" },
  { id: 369, ar: "سُوق", en: "market", tr: "sūq", unit: "10" },
  { id: 370, ar: "شاطِئ", en: "beach, shore", tr: "shāṭiʾ", unit: "10" },
  { id: 371, ar: "شِتاء", en: "winter", tr: "shitāʾ", unit: "10" },
  { id: 372, ar: "شَمال", en: "north", tr: "shamāl", unit: "10" },
  { id: 373, ar: "صِفْر", en: "zero", tr: "ṣifr", unit: "10" },
  { id: 374, ar: "صَيْف", en: "summer", tr: "ṣayf", unit: "10" },
  { id: 375, ar: "عُطْلَة الأُسْبُوع", en: "weekend", tr: "ʿuṭlat al-usbūʿ", unit: "10" },
  { id: 376, ar: "غَداً", en: "tomorrow", tr: "ghadan", unit: "10" },
  { id: 377, ar: "فَصْل الخَرِيف", en: "autumn", tr: "faṣl al-kharīf", unit: "10" },
  { id: 378, ar: "فَصْل الرَّبِيع", en: "spring", tr: "faṣl ar-rabīʿ", unit: "10" },
  { id: 379, ar: "فَصْل الشِّتاء", en: "winter (season)", tr: "faṣl ash-shitāʾ", unit: "10" },
  { id: 380, ar: "فَوْقَ", en: "above, over", tr: "fawqa", unit: "10" },
  { id: 381, ar: "فِي الخارِج", en: "outside", tr: "fī l-khārij", unit: "10" },
  { id: 382, ar: "قَضى / يَقْضِي", en: "to spend (time)", tr: "qaḍā / yaqḍī", unit: "10" },
  { id: 383, ar: "كَيْفَ", en: "how", tr: "kayfa", unit: "10" },
  { id: 384, ar: "لَيْلَة", en: "night", tr: "layla", unit: "10" },
  { id: 385, ar: "مُبْتَلّ", en: "wet", tr: "mubtall", unit: "10" },
  { id: 386, ar: "مِظَلَّة", en: "umbrella", tr: "miẓalla", unit: "10" },
  { id: 387, ar: "مُعْتَدِل", en: "mild, moderate", tr: "muʿtadil", unit: "10" },
  { id: 388, ar: "يَمِين", en: "right (direction)", tr: "yamīn", unit: "10" },
  { id: 389, ar: "ازْدِحام", en: "crowding, congestion", tr: "izdiḥām", unit: "11" },
  { id: 390, ar: "أُسْتاذ", en: "professor, sir", tr: "ustādh", unit: "11" },
  { id: 391, ar: "اسْتَغْرَقَ / يَسْتَغْرِقُ", en: "to take (time)", tr: "istaghraqa / yastaghriqu", unit: "11" },
  { id: 392, ar: "أَسْواق", en: "markets", tr: "aswāq", unit: "11" },
  { id: 393, ar: "أَصْدِقاء", en: "friends", tr: "aṣdiqāʾ", unit: "11" },
  { id: 394, ar: "انْتَقَلَ / يَنْتَقِلُ", en: "to move (house)", tr: "intaqala / yantaqilu", unit: "11" },
  { id: 395, ar: "بَحْر", en: "sea", tr: "baḥr", unit: "11" },
  { id: 396, ar: "بَلَد", en: "country, town", tr: "balad", unit: "11" },
  { id: 397, ar: "بَيْضاءُ", en: "white (f)", tr: "bayḍāʾ", unit: "11" },
  { id: 398, ar: "تَزَوَّجَ / يَتَزَوَّجُ", en: "to marry", tr: "tazawwaja / yatazawwaju", unit: "11" },
  { id: 399, ar: "تَقْرِيباً", en: "approximately", tr: "taqrīban", unit: "11" },
  { id: 400, ar: "تَلَوُّث", en: "pollution", tr: "talawwuth", unit: "11" },
  { id: 401, ar: "جِنْسِيَّة (وَثِيقَة)", en: "nationality (document)", tr: "jinsiyya", unit: "11" },
  { id: 402, ar: "جَواز سَفَر", en: "passport", tr: "jawāz safar", unit: "11" },
  { id: 403, ar: "حَمْراءُ", en: "red (f)", tr: "ḥamrāʾ", unit: "11" },
  { id: 404, ar: "خَضْراءُ", en: "green (f)", tr: "khaḍrāʾ", unit: "11" },
  { id: 405, ar: "رَأْي", en: "opinion", tr: "raʾy", unit: "11" },
  { id: 406, ar: "رِحْلَة", en: "journey, trip", tr: "riḥla", unit: "11" },
  { id: 407, ar: "زارَ / يَزُورُ", en: "to visit", tr: "zāra / yazūru", unit: "11" },
  { id: 408, ar: "زَرْقاءُ", en: "blue (f)", tr: "zarqāʾ", unit: "11" },
  { id: 409, ar: "سَنَة / سَنَوات", en: "year / years", tr: "sana / sanawāt", unit: "11" },
  { id: 410, ar: "سَوْداءُ", en: "black (f)", tr: "sawdāʾ", unit: "11" },
  { id: 411, ar: "شَرِكات", en: "companies", tr: "sharikāt", unit: "11" },
  { id: 412, ar: "صَفْراءُ", en: "yellow (f)", tr: "ṣafrāʾ", unit: "11" },
  { id: 413, ar: "ضَوْضاء", en: "noise", tr: "ḍawḍāʾ", unit: "11" },
  { id: 414, ar: "عُمْرَة", en: "umrah", tr: "ʿumra", unit: "11" },
  { id: 415, ar: "قَرْيَة", en: "village", tr: "qarya", unit: "11" },
  { id: 416, ar: "قِطار", en: "train", tr: "qiṭār", unit: "11" },
  { id: 417, ar: "لَكِنَّ", en: "but", tr: "lākinna", unit: "11" },
  { id: 418, ar: "لَيْسَ", en: "is not", tr: "laysa", unit: "11" },
  { id: 419, ar: "ما رَأْيُكَ", en: "what do you think?", tr: "mā raʾyuka", unit: "11" },
  { id: 420, ar: "مُدِير", en: "manager, director", tr: "mudīr", unit: "11" },
  { id: 421, ar: "مَدِينَة", en: "city", tr: "madīna", unit: "11" },
  { id: 422, ar: "مُشْكِلَة", en: "problem", tr: "mushkila", unit: "11" },
  { id: 423, ar: "هادِئ", en: "quiet, calm", tr: "hādiʾ", unit: "11" },
  { id: 424, ar: "هُناكَ", en: "there", tr: "hunāka", unit: "11" },
  { id: 425, ar: "هَواء", en: "air", tr: "hawāʾ", unit: "11" },
  { id: 426, ar: "أَحادِيث", en: "hadiths, sayings", tr: "aḥādīth", unit: "12" },
  { id: 427, ar: "اخْتارَ / يَخْتارُ", en: "to choose", tr: "ikhtāra / yakhtāru", unit: "12" },
  { id: 428, ar: "إِسْلامِيَّة", en: "Islamic (f)", tr: "islāmiyya", unit: "12" },
  { id: 429, ar: "أَهْوى", en: "I am keen on", tr: "ahwā", unit: "12" },
  { id: 430, ar: "آيات", en: "verses (of the Qur'an)", tr: "āyāt", unit: "12" },
  { id: 431, ar: "تَدْبِير مَنْزِلِيّ", en: "home economics", tr: "tadbīr manzilī", unit: "12" },
  { id: 432, ar: "تِلْكَ", en: "that (f)", tr: "tilka", unit: "12" },
  { id: 433, ar: "جَمْع الطَّوابِع", en: "stamp collecting", tr: "jamʿ aṭ-ṭawābiʿ", unit: "12" },
  { id: 434, ar: "جَمِيع", en: "all", tr: "jamīʿ", unit: "12" },
  { id: 435, ar: "جَناح (قِسْم)", en: "wing, hall (section)", tr: "janāḥ", unit: "12" },
  { id: 436, ar: "خَطّ الرُّقْعَة", en: "Ruqʿa script", tr: "khaṭṭ ar-ruqʿa", unit: "12" },
  { id: 437, ar: "الخَطّ العَرَبِيّ", en: "Arabic calligraphy", tr: "al-khaṭṭ al-ʿarabī", unit: "12" },
  { id: 438, ar: "خَطّ النَّسْخ", en: "Naskh script", tr: "khaṭṭ an-naskh", unit: "12" },
  { id: 439, ar: "خِياطَة", en: "sewing", tr: "khiyāṭa", unit: "12" },
  { id: 440, ar: "رِحْلات", en: "trips, excursions", tr: "riḥlāt", unit: "12" },
  { id: 441, ar: "رِياضَة", en: "sport", tr: "riyāḍa", unit: "12" },
  { id: 442, ar: "سِباحَة", en: "swimming", tr: "sibāḥa", unit: "12" },
  { id: 443, ar: "سَفَر", en: "travel", tr: "safar", unit: "12" },
  { id: 444, ar: "صِحافَة", en: "journalism", tr: "ṣiḥāfa", unit: "12" },
  { id: 445, ar: "صُحُف", en: "newspapers", tr: "ṣuḥuf", unit: "12" },
  { id: 446, ar: "طابَع", en: "stamp", tr: "ṭābaʿ", unit: "12" },
  { id: 447, ar: "طَبْع", en: "printing", tr: "ṭabʿ", unit: "12" },
  { id: 448, ar: "طَوابِع", en: "stamps", tr: "ṭawābiʿ", unit: "12" },
  { id: 449, ar: "عَرَبِيّ", en: "Arabic, Arab", tr: "ʿarabī", unit: "12" },
  { id: 450, ar: "عِلْمِيَّة", en: "scientific (f)", tr: "ʿilmiyya", unit: "12" },
  { id: 451, ar: "فُرُوسِيَّة", en: "horsemanship", tr: "furūsiyya", unit: "12" },
  { id: 452, ar: "قِراءَة", en: "reading", tr: "qirāʾa", unit: "12" },
  { id: 453, ar: "قَصِير", en: "short", tr: "qaṣīr", unit: "12" },
  { id: 454, ar: "كُتُب", en: "books", tr: "kutub", unit: "12" },
  { id: 455, ar: "كُتُب إِسْلامِيَّة", en: "Islamic books", tr: "kutub islāmiyya", unit: "12" },
  { id: 456, ar: "كُتُب عِلْمِيَّة", en: "scientific books", tr: "kutub ʿilmiyya", unit: "12" },
  { id: 457, ar: "كُرَة قَدَم", en: "football", tr: "kurat qadam", unit: "12" },
  { id: 458, ar: "كَلِمات", en: "words", tr: "kalimāt", unit: "12" },
  { id: 459, ar: "لُغَة / لُغات", en: "language / languages", tr: "lugha / lughāt", unit: "12" },
  { id: 460, ar: "مَجَلَّة / مَجَلَّات", en: "magazine / magazines", tr: "majalla / majallāt", unit: "12" },
  { id: 461, ar: "مُراسَلَة", en: "correspondence", tr: "murāsala", unit: "12" },
  { id: 462, ar: "مَعْرِض", en: "exhibition", tr: "maʿriḍ", unit: "12" },
  { id: 463, ar: "مُفِيد", en: "useful", tr: "mufīd", unit: "12" },
  { id: 464, ar: "هِوايَة", en: "hobby", tr: "hiwāya", unit: "12" },
  { id: 465, ar: "أَسابِيع", en: "weeks", tr: "asābīʿ", unit: "13" },
  { id: 466, ar: "أَقامَ / يُقِيمُ", en: "to stay, reside", tr: "aqāma / yuqīmu", unit: "13" },
  { id: 467, ar: "إِقامَة طَيِّبَة", en: "a pleasant stay", tr: "iqāma ṭayyiba", unit: "13" },
  { id: 468, ar: "بِنْت", en: "girl, daughter", tr: "bint", unit: "13" },
  { id: 469, ar: "تَأْشِيرَة خُرُوج", en: "exit visa", tr: "taʾshīrat khurūj", unit: "13" },
  { id: 470, ar: "تَأْشِيرَة دُخُول", en: "entry visa", tr: "taʾshīrat dukhūl", unit: "13" },
  { id: 471, ar: "تَأْكِيد حَجْز", en: "booking confirmation", tr: "taʾkīd ḥajz", unit: "13" },
  { id: 472, ar: "تَذاكِر", en: "tickets", tr: "tadhākir", unit: "13" },
  { id: 473, ar: "تَذْكِرَة", en: "ticket", tr: "tadhkira", unit: "13" },
  { id: 474, ar: "جَنُوب", en: "south", tr: "janūb", unit: "13" },
  { id: 475, ar: "حَجْز", en: "booking, reservation", tr: "ḥajz", unit: "13" },
  { id: 476, ar: "حَقِيبَة", en: "suitcase, bag", tr: "ḥaqība", unit: "13" },
  { id: 477, ar: "خُطُوط (طَيَران)", en: "airlines", tr: "khuṭūṭ (ṭayarān)", unit: "13" },
  { id: 478, ar: "رِحْلَة سَعِيدَة", en: "have a good trip", tr: "riḥla saʿīda", unit: "13" },
  { id: 479, ar: "زِيارَة", en: "visit", tr: "ziyāra", unit: "13" },
  { id: 480, ar: "شَرْق", en: "east", tr: "sharq", unit: "13" },
  { id: 481, ar: "ضابِط", en: "officer", tr: "ḍābiṭ", unit: "13" },
  { id: 482, ar: "عُمْرَة مَقْبُولَة", en: "may your umrah be accepted", tr: "ʿumra maqbūla", unit: "13" },
  { id: 483, ar: "غادَرَ / يُغادِرُ", en: "to depart, leave", tr: "ghādara / yughādiru", unit: "13" },
  { id: 484, ar: "غَرْب", en: "west", tr: "gharb", unit: "13" },
  { id: 485, ar: "فَتَحَ / يَفْتَحُ", en: "to open", tr: "fataḥa / yaftaḥu", unit: "13" },
  { id: 486, ar: "فَقَدَ / يَفْقِدُ", en: "to lose", tr: "faqada / yafqidu", unit: "13" },
  { id: 487, ar: "فُنْدُق", en: "hotel", tr: "funduq", unit: "13" },
  { id: 488, ar: "قادِم", en: "coming, arriving", tr: "qādim", unit: "13" },
  { id: 489, ar: "لَوْن", en: "colour", tr: "lawn", unit: "13" },
  { id: 490, ar: "مُوَظَّف", en: "employee, official", tr: "muwaẓẓaf", unit: "13" },
  { id: 491, ar: "اثْنا عَشَرَ", en: "twelve", tr: "ithnā ʿashara", unit: "14" },
  { id: 492, ar: "أَحَدَ عَشَرَ", en: "eleven", tr: "aḥada ʿashara", unit: "14" },
  { id: 493, ar: "أَرْبَعَةَ عَشَرَ", en: "fourteen", tr: "arbaʿata ʿashara", unit: "14" },
  { id: 494, ar: "أَشْواط", en: "circuits, laps", tr: "ashwāṭ", unit: "14" },
  { id: 495, ar: "اعْتَمَرَ / يَعْتَمِرُ", en: "to perform umrah", tr: "iʿtamara / yaʿtamiru", unit: "14" },
  { id: 496, ar: "بَيْنَ", en: "between", tr: "bayna", unit: "14" },
  { id: 497, ar: "تِسْعَةَ عَشَرَ", en: "nineteen", tr: "tisʿata ʿashara", unit: "14" },
  { id: 498, ar: "ثالِثَ عَشَرَ", en: "thirteenth", tr: "thālitha ʿashara", unit: "14" },
  { id: 499, ar: "ثَمانِيَةَ عَشَرَ", en: "eighteen", tr: "thamāniyata ʿashara", unit: "14" },
  { id: 500, ar: "ثَلاثَةَ عَشَرَ", en: "thirteen", tr: "thalāthata ʿashara", unit: "14" },
  { id: 501, ar: "ثَوْب الإِحْرام", en: "ihram garment", tr: "thawb al-iḥrām", unit: "14" },
  { id: 502, ar: "جَمْع", en: "combining (of prayers)", tr: "jamʿ", unit: "14" },
  { id: 503, ar: "حَلَقَ / يَحْلِقُ", en: "to shave", tr: "ḥalaqa / yaḥliqu", unit: "14" },
  { id: 504, ar: "حَوْلَ", en: "around", tr: "ḥawla", unit: "14" },
  { id: 505, ar: "خَلَعَ / يَخْلَعُ", en: "to take off (clothing)", tr: "khalaʿa / yakhlaʿu", unit: "14" },
  { id: 506, ar: "خَمْسَةَ عَشَرَ", en: "fifteen", tr: "khamsata ʿashara", unit: "14" },
  { id: 507, ar: "ذَبَحَ / يَذْبَحُ", en: "to slaughter", tr: "dhabaḥa / yadhbaḥu", unit: "14" },
  { id: 508, ar: "رَأْس / رُؤُوس", en: "head / heads", tr: "raʾs / ruʾūs", unit: "14" },
  { id: 509, ar: "رَجُل", en: "man", tr: "rajul", unit: "14" },
  { id: 510, ar: "رَكْعَة", en: "rakʿah, prayer unit", tr: "rakʿa", unit: "14" },
  { id: 511, ar: "رَمى / يَرْمِي", en: "to throw (the pebbles)", tr: "ramā / yarmī", unit: "14" },
  { id: 512, ar: "الزَّوال", en: "midday, the sun's decline", tr: "az-zawāl", unit: "14" },
  { id: 513, ar: "سَبْعَةَ عَشَرَ", en: "seventeen", tr: "sabʿata ʿashara", unit: "14" },
  { id: 514, ar: "سِتَّةَ عَشَرَ", en: "sixteen", tr: "sittata ʿashara", unit: "14" },
  { id: 515, ar: "سُرُور", en: "joy, happiness", tr: "surūr", unit: "14" },
  { id: 516, ar: "سَعى / يَسْعى", en: "to walk between Safa and Marwa", tr: "saʿā / yasʿā", unit: "14" },
  { id: 517, ar: "سَعْي", en: "the saʿy", tr: "saʿy", unit: "14" },
  { id: 518, ar: "شُرُوق (الشَّمْس)", en: "sunrise", tr: "shurūq (ash-shams)", unit: "14" },
  { id: 519, ar: "شَعَرَ / يَشْعُرُ", en: "to feel", tr: "shaʿara / yashʿuru", unit: "14" },
  { id: 520, ar: "الشَّمْس", en: "the sun", tr: "ash-shams", unit: "14" },
  { id: 521, ar: "شَوْط", en: "circuit, lap", tr: "shawṭ", unit: "14" },
  { id: 522, ar: "صامَ / يَصُومُ", en: "to fast", tr: "ṣāma / yaṣūmu", unit: "14" },
  { id: 523, ar: "الضُّحى", en: "mid-morning", tr: "aḍ-ḍuḥā", unit: "14" },
  { id: 524, ar: "طافَ / يَطُوفُ", en: "to circumambulate", tr: "ṭāfa / yaṭūfu", unit: "14" },
  { id: 525, ar: "طَواف الإِفاضَة", en: "the ifada circumambulation", tr: "ṭawāf al-ifāḍa", unit: "14" },
  { id: 526, ar: "طَواف الوَداع", en: "the farewell circumambulation", tr: "ṭawāf al-wadāʿ", unit: "14" },
  { id: 527, ar: "عَرَفات", en: "Arafat", tr: "ʿarafāt", unit: "14" },
  { id: 528, ar: "عَرَفَة", en: "the day of Arafah", tr: "ʿarafa", unit: "14" },
  { id: 529, ar: "عِنْدَ", en: "at, with", tr: "ʿinda", unit: "14" },
  { id: 530, ar: "عِيد", en: "festival, eid", tr: "ʿīd", unit: "14" },
  { id: 531, ar: "غُرُوب (الشَّمْس)", en: "sunset", tr: "ghurūb (ash-shams)", unit: "14" },
  { id: 532, ar: "الكَعْبَة", en: "the Kaaba", tr: "al-kaʿba", unit: "14" },
  { id: 533, ar: "لَبِسَ / يَلْبَسُ", en: "to wear", tr: "labisa / yalbasu", unit: "14" },
  { id: 534, ar: "لَبَّى / يُلَبِّي", en: "to say labbayk", tr: "labbā / yulabbī", unit: "14" },
  { id: 535, ar: "المَرْوَة", en: "Marwa", tr: "al-marwa", unit: "14" },
  { id: 536, ar: "مُزْدَلِفَة", en: "Muzdalifah", tr: "muzdalifa", unit: "14" },
  { id: 537, ar: "مَقام إِبْراهِيمَ", en: "the Station of Abraham", tr: "maqām ibrāhīm", unit: "14" },
  { id: 538, ar: "مِنى", en: "Mina", tr: "minā", unit: "14" },
  { id: 539, ar: "المِيقات", en: "the miqat", tr: "al-mīqāt", unit: "14" },
  { id: 540, ar: "هَدْي", en: "sacrificial animal", tr: "hady", unit: "14" },
  { id: 541, ar: "وَصَلَ / يَصِلُ", en: "to arrive", tr: "waṣala / yaṣilu", unit: "14" },
  { id: 542, ar: "وُقُوف", en: "standing (at Arafat)", tr: "wuqūf", unit: "14" },
  { id: 543, ar: "أُذُن", en: "ear", tr: "udhun", unit: "15" },
  { id: 544, ar: "أَرْبَعُونَ", en: "forty", tr: "arbaʿūn", unit: "15" },
  { id: 545, ar: "ارْتِفاع", en: "rise, height", tr: "irtifāʿ", unit: "15" },
  { id: 546, ar: "ارْتَفَعَ", en: "to rise", tr: "irtafaʿa", unit: "15" },
  { id: 547, ar: "إِسْعاف", en: "ambulance, first aid", tr: "isʿāf", unit: "15" },
  { id: 548, ar: "أَسْنان", en: "teeth", tr: "asnān", unit: "15" },
  { id: 549, ar: "أَصابَ / يُصِيبُ", en: "to afflict, strike", tr: "aṣāba / yuṣību", unit: "15" },
  { id: 550, ar: "أَلَم", en: "pain", tr: "alam", unit: "15" },
  { id: 551, ar: "أَنْف", en: "nose", tr: "anf", unit: "15" },
  { id: 552, ar: "الباقِي", en: "the rest, remainder", tr: "al-bāqī", unit: "15" },
  { id: 553, ar: "راحَة", en: "rest", tr: "rāḥa", unit: "15" },
  { id: 554, ar: "زِيادَة الوَزْن", en: "weight gain", tr: "ziyādat al-wazn", unit: "15" },
  { id: 555, ar: "سَبَب", en: "reason, cause", tr: "sabab", unit: "15" },
  { id: 556, ar: "سَبْعُونَ", en: "seventy", tr: "sabʿūn", unit: "15" },
  { id: 557, ar: "سُكَّرِيّ", en: "diabetic; diabetes", tr: "sukkarī", unit: "15" },
  { id: 558, ar: "سُكَّرِيَّات", en: "sweets, sugars", tr: "sukkariyyāt", unit: "15" },
  { id: 559, ar: "السَّلامُ عَلَيْكُم وَرَحْمَةُ اللهِ وَبَرَكاتُهُ", en: "peace, mercy and blessings of God be upon you", tr: "as-salāmu ʿalaykum wa-raḥmatu llāhi wa-barakātuh", unit: "15" },
  { id: 560, ar: "سَلِيم", en: "sound, healthy", tr: "salīm", unit: "15" },
  { id: 561, ar: "شَدِيد", en: "severe, intense", tr: "shadīd", unit: "15" },
  { id: 562, ar: "شَفاكَ اللهُ", en: "may God heal you", tr: "shafāka llāh", unit: "15" },
  { id: 563, ar: "صُداع", en: "headache", tr: "ṣudāʿ", unit: "15" },
  { id: 564, ar: "صَدْر", en: "chest", tr: "ṣadr", unit: "15" },
  { id: 565, ar: "ضَغْط", en: "pressure", tr: "ḍaghṭ", unit: "15" },
  { id: 566, ar: "طَبِيب أَسْنان", en: "dentist", tr: "ṭabīb asnān", unit: "15" },
  { id: 567, ar: "طَبِيب أَنْف وَأُذُن وَحَنْجَرَة", en: "ENT doctor", tr: "ṭabīb anf wa-udhun wa-ḥanjara", unit: "15" },
  { id: 568, ar: "طَلَب", en: "request", tr: "ṭalab", unit: "15" },
  { id: 569, ar: "عِشْرُونَ", en: "twenty", tr: "ʿishrūn", unit: "15" },
  { id: 570, ar: "فَحَصَ / يَفْحَصُ", en: "to examine", tr: "faḥaṣa / yafḥaṣu", unit: "15" },
  { id: 571, ar: "فَواكِه", en: "fruits", tr: "fawākih", unit: "15" },
  { id: 572, ar: "قابَلَ / يُقابِلُ", en: "to meet", tr: "qābala / yuqābilu", unit: "15" },
  { id: 573, ar: "قاسَ / يَقِيسُ", en: "to measure", tr: "qāsa / yaqīsu", unit: "15" },
  { id: 574, ar: "قَلْب", en: "heart", tr: "qalb", unit: "15" },
  { id: 575, ar: "كُلْيَة", en: "kidney", tr: "kulya", unit: "15" },
  { id: 576, ar: "مُمارَسَة", en: "practising, doing", tr: "mumārasa", unit: "15" },
  { id: 577, ar: "مَوْعِد", en: "appointment", tr: "mawʿid", unit: "15" },
  { id: 578, ar: "نَتِيجَة", en: "result", tr: "natīja", unit: "15" },
  { id: 579, ar: "نَصَحَ / يَنْصَحُ", en: "to advise", tr: "naṣaḥa / yanṣaḥu", unit: "15" },
  { id: 580, ar: "وَعَلَيْكُمُ السَّلامُ وَرَحْمَةُ اللهِ وَبَرَكاتُهُ", en: "and upon you peace, mercy and blessings of God", tr: "wa-ʿalaykumu s-salāmu wa-raḥmatu llāhi wa-barakātuh", unit: "15" },
  { id: 581, ar: "أَبْناء", en: "sons, children", tr: "abnāʾ", unit: "16" },
  { id: 582, ar: "إِذَنْ", en: "so, in that case", tr: "idhan", unit: "16" },
  { id: 583, ar: "الإِسْلام", en: "Islam", tr: "al-islām", unit: "16" },
  { id: 584, ar: "أُضْحِيَة", en: "sacrificial animal", tr: "uḍḥiya", unit: "16" },
  { id: 585, ar: "أَعْطى / يُعْطِي", en: "to give", tr: "aʿṭā / yuʿṭī", unit: "16" },
  { id: 586, ar: "اقْتَرَبَ / يَقْتَرِبُ", en: "to draw near", tr: "iqtaraba / yaqtaribu", unit: "16" },
  { id: 587, ar: "أَهْل", en: "family, people", tr: "ahl", unit: "16" },
  { id: 588, ar: "جِبال", en: "mountains", tr: "jibāl", unit: "16" },
  { id: 589, ar: "جُمادى الآخِرَة", en: "Jumada al-Akhirah", tr: "jumādā l-ākhira", unit: "16" },
  { id: 590, ar: "جُمادى الأُولى", en: "Jumada al-Ula", tr: "jumādā l-ūlā", unit: "16" },
  { id: 591, ar: "جَوَّالَة", en: "scouts", tr: "jawwāla", unit: "16" },
  { id: 592, ar: "حَجَّ / يَحُجُّ", en: "to perform hajj", tr: "ḥajja / yaḥujju", unit: "16" },
  { id: 593, ar: "ذُو الحِجَّة", en: "Dhu al-Hijjah", tr: "dhū l-ḥijja", unit: "16" },
  { id: 594, ar: "ذُو القَعْدَة", en: "Dhu al-Qaʿdah", tr: "dhū l-qaʿda", unit: "16" },
  { id: 595, ar: "رَأى / يَرى", en: "to see", tr: "raʾā / yarā", unit: "16" },
  { id: 596, ar: "رَبِيع الآخِر", en: "Rabiʿ al-Akhir", tr: "rabīʿ al-ākhir", unit: "16" },
  { id: 597, ar: "رَبِيع الأَوَّل", en: "Rabiʿ al-Awwal", tr: "rabīʿ al-awwal", unit: "16" },
  { id: 598, ar: "رَجَب", en: "Rajab", tr: "rajab", unit: "16" },
  { id: 599, ar: "رَخِيص", en: "cheap", tr: "rakhīṣ", unit: "16" },
  { id: 600, ar: "زَكاة الفِطْر", en: "zakat al-fitr", tr: "zakāt al-fiṭr", unit: "16" },
  { id: 601, ar: "ساعَدَ / يُساعِدُ", en: "to help", tr: "sāʿada / yusāʿidu", unit: "16" },
  { id: 602, ar: "سافَرَ / يُسافِرُ", en: "to travel", tr: "sāfara / yusāfiru", unit: "16" },
  { id: 603, ar: "شَوَّال", en: "Shawwal", tr: "shawwāl", unit: "16" },
  { id: 604, ar: "صاع", en: "saʿ (a dry measure)", tr: "ṣāʿ", unit: "16" },
  { id: 605, ar: "صَلاة العِيد", en: "the eid prayer", tr: "ṣalāt al-ʿīd", unit: "16" },
  { id: 606, ar: "عاصِمَة", en: "capital city", tr: "ʿāṣima", unit: "16" },
  { id: 607, ar: "عُطْلَة الصَّيْف", en: "summer holiday", tr: "ʿuṭlat aṣ-ṣayf", unit: "16" },
  { id: 608, ar: "عُطْلَة سَعِيدَة", en: "happy holiday", tr: "ʿuṭla saʿīda", unit: "16" },
  { id: 609, ar: "عِيد الأَضْحى", en: "Eid al-Adha", tr: "ʿīd al-aḍḥā", unit: "16" },
  { id: 610, ar: "عِيد الفِطْر", en: "Eid al-Fitr", tr: "ʿīd al-fiṭr", unit: "16" },
  { id: 611, ar: "غالٍ", en: "expensive", tr: "ghālin", unit: "16" },
  { id: 612, ar: "فَرِيق", en: "team", tr: "farīq", unit: "16" },
  { id: 613, ar: "فُقَراء", en: "the poor", tr: "fuqarāʾ", unit: "16" },
  { id: 614, ar: "قالَ / يَقُولُ", en: "to say", tr: "qāla / yaqūlu", unit: "16" },
  { id: 615, ar: "مَتاحِف", en: "museums", tr: "matāḥif", unit: "16" },
  { id: 616, ar: "مُحَرَّم", en: "Muharram", tr: "muḥarram", unit: "16" },
  { id: 617, ar: "مَزْرَعَة", en: "farm", tr: "mazraʿa", unit: "16" },
  { id: 618, ar: "مَكان", en: "place", tr: "makān", unit: "16" },
  { id: 619, ar: "مَكْتَبات", en: "libraries", tr: "maktabāt", unit: "16" },
  { id: 620, ar: "مُوافِق", en: "agreeing, in agreement", tr: "muwāfiq", unit: "16" },
  { id: 621, ar: "نَهْر", en: "river", tr: "nahr", unit: "16" },
  { id: 622, ar: "يَوْم عِيد", en: "festival day", tr: "yawm ʿīd", unit: "16" },

  // --- Tamhidi (preparatory level) glossary — 157 words, unit "T" ---
  { id: 623 , ar: "بَطاطِس", en: "potatoes", tr: "baṭāṭis", unit: "T" },
  { id: 624 , ar: "بِطِّيخة", en: "watermelon", tr: "biṭṭīkha", unit: "T" },
  { id: 625 , ar: "بُرْتُقالة", en: "an orange", tr: "burtuqāla", unit: "T" },
  { id: 626 , ar: "حَبْل", en: "rope", tr: "ḥabl", unit: "T" },
  { id: 627 , ar: "باب", en: "door", tr: "bāb", unit: "T" },
  { id: 628 , ar: "حُبوب", en: "grains", tr: "ḥubūb", unit: "T" },
  { id: 629 , ar: "فَأْر", en: "mouse", tr: "faʾr", unit: "T" },
  { id: 630 , ar: "فُجْل", en: "radish", tr: "fujl", unit: "T" },
  { id: 631 , ar: "فُسْتان", en: "dress", tr: "fustān", unit: "T" },
  { id: 632 , ar: "فول", en: "beans", tr: "fūl", unit: "T" },
  { id: 633 , ar: "فيل", en: "elephant", tr: "fīl", unit: "T" },
  { id: 634 , ar: "مِفْتاح", en: "key", tr: "miftāḥ", unit: "T" },
  { id: 635 , ar: "مُصْحَف", en: "mushaf", tr: "muṣḥaf", unit: "T" },
  { id: 636 , ar: "تَمْرة", en: "date", tr: "tamra", unit: "T" },
  { id: 637 , ar: "مال", en: "money", tr: "māl", unit: "T" },
  { id: 638 , ar: "ميزان", en: "scales", tr: "mīzān", unit: "T" },
  { id: 639 , ar: "وَلَد", en: "boy", tr: "walad", unit: "T" },
  { id: 640 , ar: "وِسادة", en: "pillow", tr: "wisāda", unit: "T" },
  { id: 641 , ar: "وَجْه", en: "face", tr: "wajh", unit: "T" },
  { id: 642 , ar: "شَوْكة", en: "fork", tr: "shawka", unit: "T" },
  { id: 643 , ar: "طاووس", en: "peacock", tr: "ṭāwūs", unit: "T" },
  { id: 644 , ar: "طَويل", en: "tall", tr: "ṭawīl", unit: "T" },
  { id: 645 , ar: "ثَعْلَب", en: "fox", tr: "thaʿlab", unit: "T" },
  { id: 646 , ar: "ثِمار", en: "fruits", tr: "thimār", unit: "T" },
  { id: 647 , ar: "ثُعْبان", en: "snake", tr: "thuʿbān", unit: "T" },
  { id: 648 , ar: "كُمَّثْرى", en: "pear", tr: "kummathrā", unit: "T" },
  { id: 649 , ar: "أَثاث", en: "furniture", tr: "athāth", unit: "T" },
  { id: 650 , ar: "ثَوْر", en: "bull", tr: "thawr", unit: "T" },
  { id: 651 , ar: "ذَيْل", en: "tail", tr: "dhayl", unit: "T" },
  { id: 652 , ar: "ذِراع", en: "arm", tr: "dhirāʿ", unit: "T" },
  { id: 653 , ar: "ذُباب", en: "flies", tr: "dhubāb", unit: "T" },
  { id: 654 , ar: "بَذْرة", en: "seed", tr: "badhra", unit: "T" },
  { id: 655 , ar: "غِذاء", en: "food", tr: "ghidhāʾ", unit: "T" },
  { id: 656 , ar: "مُذيع", en: "presenter", tr: "mudhīʿ", unit: "T" },
  { id: 657 , ar: "ظَرْف", en: "envelope", tr: "ẓarf", unit: "T" },
  { id: 658 , ar: "عَظْمة", en: "bone", tr: "ʿaẓma", unit: "T" },
  { id: 659 , ar: "مِنْظار", en: "binoculars", tr: "minẓār", unit: "T" },
  { id: 660 , ar: "مَحْظور", en: "forbidden", tr: "maḥẓūr", unit: "T" },
  { id: 661 , ar: "حَظيرة", en: "cattle shed", tr: "ḥaẓīra", unit: "T" },
  { id: 662 , ar: "تُفّاحة", en: "an apple", tr: "tuffāḥa", unit: "T" },
  { id: 663 , ar: "لِتْر", en: "litre", tr: "litr", unit: "T" },
  { id: 664 , ar: "تين", en: "fig", tr: "tīn", unit: "T" },
  { id: 665 , ar: "توت", en: "berries", tr: "tūt", unit: "T" },
  { id: 666 , ar: "دَرّاجة", en: "bicycle", tr: "darrāja", unit: "T" },
  { id: 667 , ar: "دُبّ", en: "bear", tr: "dubb", unit: "T" },
  { id: 668 , ar: "عَدَد", en: "number", tr: "ʿadad", unit: "T" },
  { id: 669 , ar: "دولاب", en: "cupboard", tr: "dūlāb", unit: "T" },
  { id: 670 , ar: "ديك", en: "rooster", tr: "dīk", unit: "T" },
  { id: 671 , ar: "طائِر", en: "bird", tr: "ṭāʾir", unit: "T" },
  { id: 672 , ar: "مَطْبَخ", en: "kitchen", tr: "maṭbakh", unit: "T" },
  { id: 673 , ar: "طاوِلة", en: "table", tr: "ṭāwila", unit: "T" },
  { id: 674 , ar: "طين", en: "mud", tr: "ṭīn", unit: "T" },
  { id: 675 , ar: "ضِرْس", en: "molar", tr: "ḍirs", unit: "T" },
  { id: 676 , ar: "ضِفْدَع", en: "frog", tr: "ḍifdaʿ", unit: "T" },
  { id: 677 , ar: "وُضوء", en: "ablution", tr: "wuḍūʾ", unit: "T" },
  { id: 678 , ar: "سِباق", en: "race", tr: "sibāq", unit: "T" },
  { id: 679 , ar: "ساعة", en: "watch", tr: "sāʿa", unit: "T" },
  { id: 680 , ar: "تِمْساح", en: "crocodile", tr: "timsāḥ", unit: "T" },
  { id: 681 , ar: "صِنّارة", en: "fishing rod", tr: "ṣinnāra", unit: "T" },
  { id: 682 , ar: "صُنْدوق", en: "box", tr: "ṣundūq", unit: "T" },
  { id: 683 , ar: "فَصْل", en: "classroom", tr: "faṣl", unit: "T" },
  { id: 684 , ar: "تَصافُح", en: "handshaking", tr: "taṣāfuḥ", unit: "T" },
  { id: 685 , ar: "عَصير", en: "juice", tr: "ʿaṣīr", unit: "T" },
  { id: 686 , ar: "زَرافة", en: "giraffe", tr: "zarāfa", unit: "T" },
  { id: 687 , ar: "زِرّ", en: "button", tr: "zirr", unit: "T" },
  { id: 688 , ar: "زُجاجة", en: "bottle", tr: "zujāja", unit: "T" },
  { id: 689 , ar: "مِزْمار", en: "oboe", tr: "mizmār", unit: "T" },
  { id: 690 , ar: "غَزال", en: "gazelle", tr: "ghazāl", unit: "T" },
  { id: 691 , ar: "سِكّين", en: "knife", tr: "sikkīn", unit: "T" },
  { id: 692 , ar: "قَلَم", en: "pen", tr: "qalam", unit: "T" },
  { id: 693 , ar: "قُفْل", en: "lock", tr: "qufl", unit: "T" },
  { id: 694 , ar: "عِقْد", en: "necklace", tr: "ʿiqd", unit: "T" },
  { id: 695 , ar: "فُلوس", en: "money", tr: "fulūs", unit: "T" },
  { id: 696 , ar: "عَقيد", en: "colonel", tr: "ʿaqīd", unit: "T" },
  { id: 697 , ar: "غُراب", en: "crow", tr: "ghurāb", unit: "T" },
  { id: 698 , ar: "مِغْرَفة", en: "ladle", tr: "mighrafa", unit: "T" },
  { id: 699 , ar: "غار", en: "cave", tr: "ghār", unit: "T" },
  { id: 700 , ar: "مَشْغول", en: "busy", tr: "mashghūl", unit: "T" },
  { id: 701 , ar: "رَغيف", en: "loaf", tr: "raghīf", unit: "T" },
  { id: 702 , ar: "نَخْلة", en: "palm tree", tr: "nakhla", unit: "T" },
  { id: 703 , ar: "خادِم", en: "servant", tr: "khādim", unit: "T" },
  { id: 704 , ar: "صَخْرة", en: "rock", tr: "ṣakhra", unit: "T" },
  { id: 705 , ar: "عَنْكَبوت", en: "spider", tr: "ʿankabūt", unit: "T" },
  { id: 706 , ar: "عِمارة", en: "block of flats", tr: "ʿimāra", unit: "T" },
  { id: 707 , ar: "عامِل", en: "worker", tr: "ʿāmil", unit: "T" },
  { id: 708 , ar: "عود", en: "oud", tr: "ʿūd", unit: "T" },
  { id: 709 , ar: "حَديقة", en: "garden", tr: "ḥadīqa", unit: "T" },
  { id: 710 , ar: "حِصان", en: "horse", tr: "ḥiṣān", unit: "T" },
  { id: 711 , ar: "صَحْن", en: "plate", tr: "ṣaḥn", unit: "T" },
  { id: 712 , ar: "حوت", en: "whale", tr: "ḥūt", unit: "T" },
  { id: 713 , ar: "هَدِيّة", en: "gift", tr: "hadiyya", unit: "T" },
  { id: 714 , ar: "هِرّة", en: "cat", tr: "hirra", unit: "T" },
  { id: 715 , ar: "هُدْهُد", en: "hoopoe", tr: "hudhud", unit: "T" },
  { id: 716 , ar: "زَهْرة", en: "flower", tr: "zahra", unit: "T" },
  { id: 717 , ar: "هاتِف", en: "telephone", tr: "hātif", unit: "T" },
  { id: 718 , ar: "شَهْر", en: "month", tr: "shahr", unit: "T" },
  { id: 719 , ar: "بَهيمة", en: "cattle", tr: "bahīma", unit: "T" },
  { id: 720 , ar: "أَسَد", en: "lion", tr: "asad", unit: "T" },
  { id: 721 , ar: "إِبْرة", en: "needle", tr: "ibra", unit: "T" },
  { id: 722 , ar: "آدَم", en: "Adam", tr: "ādam", unit: "T" },
  { id: 723 , ar: "رَئيس", en: "boss", tr: "raʾīs", unit: "T" },
  { id: 724 , ar: "مَساء", en: "evening", tr: "masāʾ", unit: "T" },
  { id: 725 , ar: "ظُهْرًا", en: "at noon", tr: "ẓuhran", unit: "T" },
  { id: 726 , ar: "عَصْرًا", en: "late afternoon", tr: "ʿaṣran", unit: "T" },
  { id: 727 , ar: "البارِحة", en: "yesterday", tr: "al-bāriḥa", unit: "T" },
  { id: 728 , ar: "اللَّيْلة", en: "tonight", tr: "al-layla", unit: "T" },
  { id: 729 , ar: "زينة", en: "decorations", tr: "zīna", unit: "T" },
  { id: 730 , ar: "خِنْزير", en: "pig", tr: "khinzīr", unit: "T" },
  { id: 731 , ar: "رُمّان", en: "pomegranate", tr: "rummān", unit: "T" },
  { id: 732 , ar: "قِرْد", en: "monkey", tr: "qird", unit: "T" },
  { id: 733 , ar: "لَيْمون", en: "lemon", tr: "laymūn", unit: "T" },
  { id: 734 , ar: "لِسان", en: "tongue", tr: "lisān", unit: "T" },
  { id: 735 , ar: "لُعْبة", en: "toy", tr: "luʿba", unit: "T" },
  { id: 736 , ar: "كَلْب", en: "dog", tr: "kalb", unit: "T" },
  { id: 737 , ar: "لوبِياء", en: "black-eyed beans", tr: "lūbiyāʾ", unit: "T" },
  { id: 738 , ar: "صَيْدَلِيّة", en: "pharmacy", tr: "ṣaydaliyya", unit: "T" },
  { id: 739 , ar: "مِكْنَسة", en: "vacuum cleaner", tr: "miknasa", unit: "T" },
  { id: 740 , ar: "نَسْر", en: "eagle", tr: "nasr", unit: "T" },
  { id: 741 , ar: "نافِذة", en: "window", tr: "nāfidha", unit: "T" },
  { id: 742 , ar: "ناقة", en: "she-camel", tr: "nāqa", unit: "T" },
  { id: 743 , ar: "كَنيسة", en: "church", tr: "kanīsa", unit: "T" },
  { id: 744 , ar: "جَزَرة", en: "carrot", tr: "jazara", unit: "T" },
  { id: 745 , ar: "جِذْر", en: "root", tr: "jidhr", unit: "T" },
  { id: 746 , ar: "جُبْن", en: "cheese", tr: "jubn", unit: "T" },
  { id: 747 , ar: "جوع", en: "hunger", tr: "jūʿ", unit: "T" },
  { id: 748 , ar: "شِراع", en: "sail", tr: "shirāʿ", unit: "T" },
  { id: 749 , ar: "شُرْطِيّ", en: "policeman", tr: "shurṭī", unit: "T" },
  { id: 750 , ar: "قُشور", en: "peel", tr: "qushūr", unit: "T" },
  { id: 751 , ar: "حَشيش", en: "grass", tr: "ḥashīsh", unit: "T" },
  { id: 752 , ar: "يَد", en: "hand", tr: "yad", unit: "T" },
  { id: 753 , ar: "زَيْتون", en: "olives", tr: "zaytūn", unit: "T" },
  { id: 754 , ar: "مِذْياع", en: "radio", tr: "midhyāʿ", unit: "T" },
  { id: 755 , ar: "يوسُف", en: "Yusuf", tr: "yūsuf", unit: "T" },
  { id: 756 , ar: "مَقاييس", en: "standards", tr: "maqāyīs", unit: "T" },
  { id: 757 , ar: "كَأْس", en: "cup", tr: "kaʾs", unit: "T" },
  { id: 758 , ar: "كُرْسِيّ", en: "chair", tr: "kursī", unit: "T" },
  { id: 759 , ar: "كوخ", en: "hut", tr: "kūkh", unit: "T" },
  { id: 760 , ar: "اليَوْم", en: "today", tr: "al-yawm", unit: "T" },
  { id: 761 , ar: "الأُسْبوع", en: "week", tr: "al-usbūʿ", unit: "T" },
  { id: 762 , ar: "اللَّيْل", en: "night", tr: "al-layl", unit: "T" },
  { id: 763 , ar: "النَّهار", en: "daytime", tr: "an-nahār", unit: "T" },
  { id: 764 , ar: "الماضي", en: "the past", tr: "al-māḍī", unit: "T" },
  { id: 765 , ar: "الحاضِر", en: "the present", tr: "al-ḥāḍir", unit: "T" },
  { id: 766 , ar: "المُسْتَقْبَل", en: "the future", tr: "al-mustaqbal", unit: "T" },
  { id: 767 , ar: "يُمْسِك", en: "he holds", tr: "yumsik", unit: "T" },
  { id: 768 , ar: "يَأْخُذ", en: "he takes", tr: "yaʾkhudh", unit: "T" },
  { id: 769 , ar: "يَبيع", en: "he sells", tr: "yabīʿ", unit: "T" },
  { id: 770 , ar: "يَرْكَب", en: "he rides", tr: "yarkab", unit: "T" },
  { id: 771 , ar: "يَصْطاد", en: "he hunts", tr: "yaṣṭād", unit: "T" },
  { id: 772 , ar: "يُريد", en: "he wants", tr: "yurīd", unit: "T" },
  { id: 773 , ar: "يَحْمِل", en: "he carries", tr: "yaḥmil", unit: "T" },
  { id: 774 , ar: "يُفَكِّر", en: "he thinks", tr: "yufakkir", unit: "T" },
  { id: 775 , ar: "يَجْمَع", en: "he collects", tr: "yajmaʿ", unit: "T" },
  { id: 776 , ar: "يَبْني", en: "he builds", tr: "yabnī", unit: "T" },
  { id: 777 , ar: "يَلْعَب", en: "he plays", tr: "yalʿab", unit: "T" },
  { id: 778 , ar: "يَقِف", en: "he stands", tr: "yaqif", unit: "T" },
  { id: 779 , ar: "يَتَحَدَّث", en: "he speaks", tr: "yataḥaddath", unit: "T" },
];
